/*
 * Generates sixes.js (window.SIXES) for Six of a Kind — run `node build_sixes.js`.
 *
 * Each puzzle is ONE category made of two of The Grid's criteria:
 *   club × nationality   "A Serbian who played for FC Barcelona"
 *   club × position      "A Center who played for CSKA Moscow"
 *   club × club          "Played for Olympiacos and Panathinaikos"
 *   nationality × position  "A Greek Guard"
 * and the player has to name any SIX players who fit it.
 *
 * IMPORTANT: like build_grids.js this loads the REAL thegrid.js and asks its
 * _answers hook, so the generator and the game share ONE definition of "played
 * for club X" — sixofakind.js checks guesses through the same hook.
 *
 * Guarantee per category: at least MIN_ANSWERS players fit, so six is hard but
 * never impossible, and at most MAX_ANSWERS, so it is never a giveaway.
 *
 * The bank is written in a fixed, seeded order. Never regenerate it mid-season
 * without reason: the Daily picks by index, so a reshuffle changes today's
 * category for anyone who has not played it yet (a played daily keeps its own
 * category in its save).
 */
"use strict";
const fs = require("fs");

global.window = {
  addEventListener: function () {},
  localStorage: { getItem: function () { return null; }, setItem: function () {}, removeItem: function () {} }
};
global.document = {
  readyState: "complete",
  addEventListener: function () {},
  getElementById: function () { return null; },
  createElement: function () { return {}; },
  querySelector: function () { return null; }
};
eval(fs.readFileSync("players.js", "utf8"));
eval(fs.readFileSync("legends.js", "utf8"));
eval(fs.readFileSync("careers.js", "utf8"));
eval(fs.readFileSync("lineups.js", "utf8"));
eval(fs.readFileSync("clubs.js", "utf8"));   // same-club era names fold exactly as they do in the game
window.GRIDS = [];
eval(fs.readFileSync("thegrid.js", "utf8"));
const G = window.TheGrid;

// --- Tuning knobs -------------------------------------------------------------
const MIN_ANSWERS = 10, MAX_ANSWERS = 40;
const CLUB_MIN = 6;                      // careers through a club before it can be a criterion
const NAT_MIN = 6;
const SEED = 20260930;

function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rnd = mulberry32(SEED);
function shuffle(a) { for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(rnd() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; } return a; }

// --- Candidate criteria (the same filters build_grids.js uses) ------------------
const U = G._universe();
const clubCount = {}, natCount = {};
for (const name in U) {
  const e = U[name];
  for (const c in e.clubs) clubCount[c] = (clubCount[c] || 0) + 1;
  if (e.nat) natCount[e.nat] = (natCount[e.nat] || 0) + 1;
}
// EuroLeague clubs only, canonical names only (Tau Ceramica answers, Baskonia asks).
const canonicalOnly = c => !window.CLUBS || window.CLUBS.canonical(c) === c;
const CLUBS = Object.keys(clubCount).filter(c => window.TEAMS[c] && canonicalOnly(c) && clubCount[c] >= CLUB_MIN).sort();
const NATS = Object.keys(natCount).filter(n => natCount[n] >= NAT_MIN).sort();
const POSITIONS = ["Guard", "Forward", "Center"];

const byType = { nat: [], pos: [], club: [], natpos: [] };
function consider(type, a, b) {
  const n = G._answers(a, b, true).length;   // the known players: the game also counts the archive's
  if (n >= MIN_ANSWERS && n <= MAX_ANSWERS) byType[type].push({ a, b });
}
CLUBS.forEach(function (c) {
  const A = { t: "club", v: c };
  NATS.forEach(n => consider("nat", A, { t: "nat", v: n }));
  POSITIONS.forEach(p => consider("pos", A, { t: "pos", v: p }));
  CLUBS.forEach(function (d) { if (d > c) consider("club", A, { t: "club", v: d }); });
});
NATS.forEach(function (n) { POSITIONS.forEach(p => consider("natpos", { t: "nat", v: n }, { t: "pos", v: p })); });

// Interleave the types so consecutive days feel different, each list shuffled.
Object.keys(byType).forEach(k => shuffle(byType[k]));
const order = ["pos", "nat", "club", "natpos"];
const total = order.reduce((s, k) => s + byType[k].length, 0);
console.log("categories: " + order.map(k => k + " " + byType[k].length).join(", "));
const puzzles = [];
for (let i = 0; puzzles.length < total; i++) {
  const list = byType[order[i % order.length]];
  if (list.length) puzzles.push(list.shift());
}
if (puzzles.length < 60) { console.error("too few categories — loosen the knobs"); process.exit(1); }

const out = "/* AUTO-GENERATED by build_sixes.js — do not edit by hand. Categories for Six of a Kind. */\n" +
  "window.SIXES = [\n" +
  puzzles.map(p => "  " + JSON.stringify(p)).join(",\n") +
  "\n];\n";
fs.writeFileSync("sixes.js", out);
console.log("wrote sixes.js (" + puzzles.length + " categories)");
