/*
 * Builds eurocup_players.js, the EuroCup roster database.
 *
 *   Run:  node build_eurocup.js
 *
 * The EuroCup is Euroball's second competition. Its rosters are kept apart from
 * the EuroLeague's (players.js) because the two are different games' worth of
 * players: the switcher on the hub picks one, and competition.js hands the
 * chosen one to every game as window.PLAYERS / window.TEAMS.
 *
 * TEAMS and PLAYERS below are the source, filled in club by club from the
 * official rosters (same routine as the EuroLeague season update). Records use
 * players.js's shape: name, team, nationality, position (Guard/Forward/Center),
 * height (cm), birthYear, number. While PLAYERS is empty the EuroCup stays a
 * "coming soon" page and nothing on the site changes.
 */
const fs = require("fs");

const SEASON = "2026-27";

// club name → { country }
const TEAMS = {
};

// { name, team, nationality, position, height, birthYear, number }
const PLAYERS = [
];

const POSITIONS = { Guard: 1, Forward: 1, Center: 1 };
const problems = [];
const seen = {};
PLAYERS.forEach(function (p, i) {
  const at = (p && p.name) || "#" + i;
  ["name", "team", "nationality", "position"].forEach(function (k) {
    if (typeof p[k] !== "string" || !p[k]) problems.push(at + ": missing " + k);
  });
  if (!TEAMS[p.team]) problems.push(at + ": club '" + p.team + "' is not in TEAMS");
  if (!POSITIONS[p.position]) problems.push(at + ": position '" + p.position + "' is not Guard/Forward/Center");
  if (!(p.height >= 160 && p.height <= 235)) problems.push(at + ": height " + p.height);
  if (!(p.birthYear >= 1975 && p.birthYear <= 2010)) problems.push(at + ": birthYear " + p.birthYear);
  if (!(p.number >= 0 && p.number <= 99)) problems.push(at + ": number " + p.number);
  if (seen[p.name]) problems.push(at + ": listed twice");
  seen[p.name] = 1;
});
if (problems.length) {
  console.error("eurocup_players.js NOT written:\n  " + problems.join("\n  "));
  process.exit(1);
}

const players = PLAYERS.slice().sort(function (a, b) {
  return a.team === b.team ? a.name.localeCompare(b.name) : a.team.localeCompare(b.team);
}).map(function (p) {
  return { name: p.name, team: p.team, nationality: p.nationality, position: p.position,
           height: p.height, birthYear: p.birthYear, number: p.number };
});

const out = "/*\n" +
  " * EuroCup " + SEASON + " player database (auto-generated by build_eurocup.js — do not edit).\n" +
  " * Same record shape as players.js. Empty until the rosters are researched; while\n" +
  " * it is empty the EuroCup stays a coming-soon page.\n" +
  " */\n\n" +
  "window.EUROCUP_TEAMS = " + JSON.stringify(TEAMS, null, 2) + ";\n\n" +
  "window.EUROCUP_PLAYERS = " + JSON.stringify(players, null, 2) + ";\n";
fs.writeFileSync("eurocup_players.js", out);
console.log("eurocup_players.js: " + Object.keys(TEAMS).length + " clubs, " + players.length + " players");
