/*
 * EuroCup 2026-27 player database (auto-generated by build_eurocup.js — do not edit).
 * Same record shape as players.js. Until EUROCUP_OPEN is true the EuroCup stays
 * a coming-soon page.
 */

window.EUROCUP_OPEN = false;

window.EUROCUP_TEAMS = {
  "Aris Thessaloniki": {
    "country": "Greece"
  }
};

window.EUROCUP_PLAYERS = [
  {
    "name": "Khem Birch",
    "team": "Aris Thessaloniki",
    "nationality": "Canada",
    "position": "Center",
    "height": 206,
    "birthYear": 1992,
    "number": 92
  },
  {
    "name": "Matt Morgan",
    "team": "Aris Thessaloniki",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1997,
    "number": 30
  },
  {
    "name": "Neno Dimitrijevic",
    "team": "Aris Thessaloniki",
    "nationality": "North Macedonia",
    "position": "Guard",
    "height": 190,
    "birthYear": 1998,
    "number": 7
  },
  {
    "name": "Stefan Jovic",
    "team": "Aris Thessaloniki",
    "nationality": "Serbia",
    "position": "Guard",
    "height": 198,
    "birthYear": 1990,
    "number": 24
  },
  {
    "name": "Vassilis Toliopoulos",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Guard",
    "height": 188,
    "birthYear": 1996,
    "number": 4
  }
];
