/*
 * EuroCup 2026-27 player database (auto-generated by build_eurocup.js — do not edit).
 * Same record shape as players.js. Until EUROCUP_OPEN is true the EuroCup stays
 * a coming-soon page.
 */

window.EUROCUP_OPEN = false;

window.EUROCUP_TEAMS = {
  "Aris Thessaloniki": {
    "country": "Greece"
  },
  "Derthona Tortona": {
    "country": "Italy"
  },
  "Bahcesehir College": {
    "country": "Turkey"
  },
  "Balkan Botevgrad": {
    "country": "Bulgaria"
  },
  "Bosna Sarajevo": {
    "country": "Bosnia and Herzegovina"
  },
  "Buducnost": {
    "country": "Montenegro"
  },
  "Cedevita Olimpija": {
    "country": "Slovenia"
  },
  "JL Bourg-en-Bresse": {
    "country": "France"
  },
  "Trento": {
    "country": "Italy"
  },
  "Hapoel Jerusalem": {
    "country": "Israel"
  },
  "Manresa": {
    "country": "Spain"
  },
  "La Laguna Tenerife": {
    "country": "Spain"
  },
  "Le Mans": {
    "country": "France"
  },
  "Lietkabelis": {
    "country": "Lithuania"
  },
  "London Lions": {
    "country": "United Kingdom"
  },
  "Maxima Roma": {
    "country": "Italy"
  },
  "Napoli Basketball": {
    "country": "Italy"
  },
  "Neptunas": {
    "country": "Lithuania"
  },
  "Niners Chemnitz": {
    "country": "Germany"
  },
  "PAOK": {
    "country": "Greece"
  },
  "Ratiopharm Ulm": {
    "country": "Germany"
  },
  "San Pablo Burgos": {
    "country": "Spain"
  },
  "Riga Zelli": {
    "country": "Latvia"
  },
  "Roma Basketball": {
    "country": "Italy"
  },
  "Rostock Seawolves": {
    "country": "Germany"
  },
  "Siauliai": {
    "country": "Lithuania"
  },
  "Skyliners Frankfurt": {
    "country": "Germany"
  },
  "Slask Wroclaw": {
    "country": "Poland"
  },
  "Tofas": {
    "country": "Turkey"
  },
  "Turk Telekom": {
    "country": "Turkey"
  },
  "Cluj-Napoca": {
    "country": "Romania"
  },
  "Reyer Venezia": {
    "country": "Italy"
  }
};

window.EUROCUP_PLAYERS = [
  {
    "name": "Adam Mokoka",
    "team": "Aris Thessaloniki",
    "nationality": "France",
    "position": "Forward",
    "height": 196,
    "birthYear": 1998,
    "number": 95
  },
  {
    "name": "E.J. Liddell",
    "team": "Aris Thessaloniki",
    "nationality": "USA",
    "position": "Forward",
    "height": 198,
    "birthYear": 2000,
    "number": 32
  },
  {
    "name": "Eleftherios Bochoridis",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Guard",
    "height": 196,
    "birthYear": 1994,
    "number": 13
  },
  {
    "name": "Elijah Mitrou-Long",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Guard",
    "height": 187,
    "birthYear": 1996,
    "number": 0
  },
  {
    "name": "Georgios Tanoulis",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Center",
    "height": 210,
    "birthYear": 2002,
    "number": 50
  },
  {
    "name": "Jeremiah Robinson-Earl",
    "team": "Aris Thessaloniki",
    "nationality": "USA",
    "position": "Forward",
    "height": 206,
    "birthYear": 2000,
    "number": 3
  },
  {
    "name": "Khem Birch",
    "team": "Aris Thessaloniki",
    "nationality": "Canada",
    "position": "Center",
    "height": 206,
    "birthYear": 1992,
    "number": 92
  },
  {
    "name": "Kostas Antetokounmpo",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Center",
    "height": 208,
    "birthYear": 1997,
    "number": 37
  },
  {
    "name": "Matt Morgan",
    "team": "Aris Thessaloniki",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1997,
    "number": 30
  },
  {
    "name": "Neno Dimitrijevic",
    "team": "Aris Thessaloniki",
    "nationality": "North Macedonia",
    "position": "Guard",
    "height": 190,
    "birthYear": 1998,
    "number": 7
  },
  {
    "name": "Stefan Jovic",
    "team": "Aris Thessaloniki",
    "nationality": "Serbia",
    "position": "Guard",
    "height": 198,
    "birthYear": 1990,
    "number": 24
  },
  {
    "name": "Stylianos Poulianitis",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Guard",
    "height": 190,
    "birthYear": 1995,
    "number": 11
  },
  {
    "name": "Thanasis Antetokounmpo",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Forward",
    "height": 201,
    "birthYear": 1992,
    "number": 43
  },
  {
    "name": "Vasilis Charalampopoulos",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Forward",
    "height": 204,
    "birthYear": 1997,
    "number": 33
  },
  {
    "name": "Vassilis Toliopoulos",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Guard",
    "height": 188,
    "birthYear": 1996,
    "number": 4
  },
  {
    "name": "Aleksa Avramovic",
    "team": "Bahcesehir College",
    "nationality": "Serbia",
    "position": "Guard",
    "height": 193,
    "birthYear": 1994,
    "number": 4
  },
  {
    "name": "Damien Inglis",
    "team": "Bahcesehir College",
    "nationality": "France",
    "position": "Center",
    "height": 203,
    "birthYear": 1995,
    "number": 7
  },
  {
    "name": "David DiLeo",
    "team": "Bahcesehir College",
    "nationality": "USA",
    "position": "Forward",
    "height": 203,
    "birthYear": 1997,
    "number": 51
  },
  {
    "name": "Furkan Haltali",
    "team": "Bahcesehir College",
    "nationality": "Turkey",
    "position": "Center",
    "height": 211,
    "birthYear": 2002,
    "number": 14
  },
  {
    "name": "Isiaha Mike",
    "team": "Bahcesehir College",
    "nationality": "Canada",
    "position": "Forward",
    "height": 203,
    "birthYear": 1997,
    "number": 24
  },
  {
    "name": "Ismet Akpinar",
    "team": "Bahcesehir College",
    "nationality": "Germany",
    "position": "Guard",
    "height": 191,
    "birthYear": 1995,
    "number": 5
  },
  {
    "name": "Kenan Sipahi",
    "team": "Bahcesehir College",
    "nationality": "Turkey",
    "position": "Guard",
    "height": 197,
    "birthYear": 1995,
    "number": 55
  },
  {
    "name": "Malachi Flynn",
    "team": "Bahcesehir College",
    "nationality": "Turkey",
    "position": "Guard",
    "height": 185,
    "birthYear": 1998,
    "number": 22
  },
  {
    "name": "Marcquise Reed",
    "team": "Bahcesehir College",
    "nationality": "Georgia",
    "position": "Guard",
    "height": 191,
    "birthYear": 1995,
    "number": 0
  },
  {
    "name": "Mateusz Ponitka",
    "team": "Bahcesehir College",
    "nationality": "Poland",
    "position": "Forward",
    "height": 198,
    "birthYear": 1993,
    "number": 38
  },
  {
    "name": "Maxim Mutaf",
    "team": "Bahcesehir College",
    "nationality": "Turkey",
    "position": "Forward",
    "height": 193,
    "birthYear": 1991,
    "number": 17
  },
  {
    "name": "Trevion Williams",
    "team": "Bahcesehir College",
    "nationality": "USA",
    "position": "Center",
    "height": 206,
    "birthYear": 2000,
    "number": 50
  },
  {
    "name": "Tyler Cavanaugh",
    "team": "Bahcesehir College",
    "nationality": "USA",
    "position": "Forward",
    "height": 206,
    "birthYear": 1994,
    "number": 34
  },
  {
    "name": "Aleksandar Stoimenov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Guard",
    "height": 198,
    "birthYear": 2001,
    "number": 3
  },
  {
    "name": "Alex Ducas",
    "team": "Balkan Botevgrad",
    "nationality": "Australia",
    "position": "Forward",
    "height": 201,
    "birthYear": 2000,
    "number": 8
  },
  {
    "name": "Darnell Edge",
    "team": "Balkan Botevgrad",
    "nationality": "USA",
    "position": "Guard",
    "height": 185,
    "birthYear": 1997,
    "number": 1
  },
  {
    "name": "David Okwera",
    "team": "Balkan Botevgrad",
    "nationality": "Australia",
    "position": "Forward",
    "height": 208,
    "birthYear": 2002,
    "number": 0
  },
  {
    "name": "Dimitar Dimitrov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Forward",
    "height": 203,
    "birthYear": 1993,
    "number": 34
  },
  {
    "name": "Gael Bonilla",
    "team": "Balkan Botevgrad",
    "nationality": "Mexico",
    "position": "Forward",
    "height": 203,
    "birthYear": 2003,
    "number": 2
  },
  {
    "name": "Ivan Alipiev",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Forward",
    "height": 200,
    "birthYear": 1999,
    "number": 35
  },
  {
    "name": "Ivan Spirov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Forward",
    "height": 203,
    "birthYear": 2003,
    "number": 91
  },
  {
    "name": "Javante McCoy",
    "team": "Balkan Botevgrad",
    "nationality": "USA",
    "position": "Guard",
    "height": 196,
    "birthYear": 1998,
    "number": 13
  },
  {
    "name": "Konstantin Toshkov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Guard",
    "height": 186,
    "birthYear": 2002,
    "number": 22
  },
  {
    "name": "Martin Sotirov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Forward",
    "height": 201,
    "birthYear": 1999,
    "number": 44
  },
  {
    "name": "Nikolay Grozev",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Forward",
    "height": 198,
    "birthYear": 1994,
    "number": 33
  },
  {
    "name": "Pavlin Ivanov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Guard",
    "height": 196,
    "birthYear": 1993,
    "number": 10
  },
  {
    "name": "Ulrich Chomche",
    "team": "Balkan Botevgrad",
    "nationality": "Cameroon",
    "position": "Center",
    "height": 211,
    "birthYear": 2005,
    "number": 14
  },
  {
    "name": "Adin Vrabac",
    "team": "Bosna Sarajevo",
    "nationality": "Bosnia and Herzegovina",
    "position": "Guard",
    "height": 206,
    "birthYear": 1994,
    "number": 7
  },
  {
    "name": "Alija Islamovic",
    "team": "Bosna Sarajevo",
    "nationality": "Bosnia and Herzegovina",
    "position": "Center",
    "height": 207,
    "birthYear": 2001,
    "number": 33
  },
  {
    "name": "Darko Talic",
    "team": "Bosna Sarajevo",
    "nationality": "Bosnia and Herzegovina",
    "position": "Guard",
    "height": 192,
    "birthYear": 1998,
    "number": 19
  },
  {
    "name": "DeAndre Gholston",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Guard",
    "height": 196,
    "birthYear": 2000,
    "number": 4
  },
  {
    "name": "Edin Atic",
    "team": "Bosna Sarajevo",
    "nationality": "Bosnia and Herzegovina",
    "position": "Guard",
    "height": 201,
    "birthYear": 1997,
    "number": 5
  },
  {
    "name": "Gary Browne",
    "team": "Bosna Sarajevo",
    "nationality": "Puerto Rico",
    "position": "Guard",
    "height": 185,
    "birthYear": 1993,
    "number": 14
  },
  {
    "name": "James Banks",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Center",
    "height": 208,
    "birthYear": 1998,
    "number": 1
  },
  {
    "name": "Marcus Domask",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Guard",
    "height": 198,
    "birthYear": 2000,
    "number": 3
  },
  {
    "name": "Nikola Popovic",
    "team": "Bosna Sarajevo",
    "nationality": "Serbia",
    "position": "Center",
    "height": 211,
    "birthYear": 1997,
    "number": 21
  },
  {
    "name": "Reginald Perry",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Center",
    "height": 203,
    "birthYear": 2000,
    "number": 11
  },
  {
    "name": "Ryan Hawkins",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1997,
    "number": 44
  },
  {
    "name": "Shawn Pipes Jr.",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 1999,
    "number": 2
  },
  {
    "name": "Andrija Slavkovic",
    "team": "Buducnost",
    "nationality": "Montenegro",
    "position": "Forward",
    "height": 201,
    "birthYear": 1999,
    "number": 7
  },
  {
    "name": "Axel Bouteille",
    "team": "Buducnost",
    "nationality": "France",
    "position": "Forward",
    "height": 201,
    "birthYear": 1995,
    "number": 83
  },
  {
    "name": "Dordije Jovanovic",
    "team": "Buducnost",
    "nationality": "Montenegro",
    "position": "Forward",
    "height": 197,
    "birthYear": 2003,
    "number": 13
  },
  {
    "name": "Emir Hadzibegovic",
    "team": "Buducnost",
    "nationality": "Montenegro",
    "position": "Forward",
    "height": 206,
    "birthYear": 1996,
    "number": 8
  },
  {
    "name": "Fletcher Magee",
    "team": "Buducnost",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1996,
    "number": 3
  },
  {
    "name": "Iverson Molinar",
    "team": "Buducnost",
    "nationality": "Panama",
    "position": "Guard",
    "height": 191,
    "birthYear": 1999,
    "number": 10
  },
  {
    "name": "Jerry Boutsiele",
    "team": "Buducnost",
    "nationality": "France",
    "position": "Center",
    "height": 208,
    "birthYear": 1992,
    "number": 16
  },
  {
    "name": "Justin Smith",
    "team": "Buducnost",
    "nationality": "USA",
    "position": "Center",
    "height": 201,
    "birthYear": 1999,
    "number": 0
  },
  {
    "name": "Juwan Morgan",
    "team": "Buducnost",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1997,
    "number": 15
  },
  {
    "name": "Marial Shayok",
    "team": "Buducnost",
    "nationality": "South Sudan",
    "position": "Forward",
    "height": 196,
    "birthYear": 1995,
    "number": 1
  },
  {
    "name": "Oleksandr Kovliar",
    "team": "Buducnost",
    "nationality": "Ukraine",
    "position": "Forward",
    "height": 191,
    "birthYear": 2002,
    "number": 50
  },
  {
    "name": "Stefan Dordevic",
    "team": "Buducnost",
    "nationality": "Serbia",
    "position": "Center",
    "height": 206,
    "birthYear": 1998,
    "number": 45
  },
  {
    "name": "Yogi Ferrell",
    "team": "Buducnost",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 1993,
    "number": 11
  },
  {
    "name": "Anthony Cowan Jr.",
    "team": "Cedevita Olimpija",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 1997,
    "number": 1
  },
  {
    "name": "David Skara",
    "team": "Cedevita Olimpija",
    "nationality": "Croatia",
    "position": "Center",
    "height": 203,
    "birthYear": 1995,
    "number": 24
  },
  {
    "name": "Jaka Blazic",
    "team": "Cedevita Olimpija",
    "nationality": "Slovenia",
    "position": "Guard",
    "height": 196,
    "birthYear": 1990,
    "number": 11
  },
  {
    "name": "Jayce Johnson",
    "team": "Cedevita Olimpija",
    "nationality": "USA",
    "position": "Center",
    "height": 213,
    "birthYear": 1997,
    "number": 34
  },
  {
    "name": "Jordan Gainey",
    "team": "Cedevita Olimpija",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 2002,
    "number": 4
  },
  {
    "name": "Matthew Hurt",
    "team": "Cedevita Olimpija",
    "nationality": "USA",
    "position": "Forward",
    "height": 206,
    "birthYear": 2000,
    "number": 21
  },
  {
    "name": "Miha Cerkvenik",
    "team": "Cedevita Olimpija",
    "nationality": "Slovenia",
    "position": "Forward",
    "height": 201,
    "birthYear": 2001,
    "number": 20
  },
  {
    "name": "Noah Kirkwood",
    "team": "Cedevita Olimpija",
    "nationality": "Canada",
    "position": "Forward",
    "height": 201,
    "birthYear": 1999,
    "number": 22
  },
  {
    "name": "Osayi Osifo",
    "team": "Cedevita Olimpija",
    "nationality": "South Africa",
    "position": "Center",
    "height": 206,
    "birthYear": 2000,
    "number": 14
  },
  {
    "name": "Rihards Lomazs",
    "team": "Cedevita Olimpija",
    "nationality": "Latvia",
    "position": "Guard",
    "height": 193,
    "birthYear": 1996,
    "number": 6
  },
  {
    "name": "Rok Radovic",
    "team": "Cedevita Olimpija",
    "nationality": "Slovenia",
    "position": "Forward",
    "height": 201,
    "birthYear": 2001,
    "number": 3
  },
  {
    "name": "Urban Kroflic",
    "team": "Cedevita Olimpija",
    "nationality": "Slovenia",
    "position": "Guard",
    "height": 198,
    "birthYear": 2006,
    "number": 23
  },
  {
    "name": "Aljami Durham",
    "team": "Derthona Tortona",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1998,
    "number": 42
  },
  {
    "name": "Amar Alibegovic",
    "team": "Derthona Tortona",
    "nationality": "Bosnia and Herzegovina",
    "position": "Forward",
    "height": 206,
    "birthYear": 1995,
    "number": 7
  },
  {
    "name": "Andrea Pecchia",
    "team": "Derthona Tortona",
    "nationality": "Italy",
    "position": "Guard",
    "height": 196,
    "birthYear": 1997,
    "number": 6
  },
  {
    "name": "Dante Maddox Jr.",
    "team": "Derthona Tortona",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 2002,
    "number": 21
  },
  {
    "name": "Dominik Olejniczak",
    "team": "Derthona Tortona",
    "nationality": "Poland",
    "position": "Center",
    "height": 213,
    "birthYear": 1996,
    "number": 17
  },
  {
    "name": "Giordano Bortolani",
    "team": "Derthona Tortona",
    "nationality": "Italy",
    "position": "Guard",
    "height": 193,
    "birthYear": 2000,
    "number": 12
  },
  {
    "name": "Giulio Gazzotti",
    "team": "Derthona Tortona",
    "nationality": "Italy",
    "position": "Forward",
    "height": 203,
    "birthYear": 1991,
    "number": 24
  },
  {
    "name": "Justin Gorham",
    "team": "Derthona Tortona",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1998,
    "number": 4
  },
  {
    "name": "Karim Jallow",
    "team": "Derthona Tortona",
    "nationality": "Germany",
    "position": "Forward",
    "height": 198,
    "birthYear": 1997,
    "number": 35
  },
  {
    "name": "Paul Eboua",
    "team": "Derthona Tortona",
    "nationality": "Cameroon",
    "position": "Forward",
    "height": 203,
    "birthYear": 2000,
    "number": 0
  },
  {
    "name": "Prentiss Hubb",
    "team": "Derthona Tortona",
    "nationality": "USA",
    "position": "Guard",
    "height": 191,
    "birthYear": 1999,
    "number": 3
  },
  {
    "name": "Jaleen Smith",
    "team": "Hapoel Jerusalem",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1994,
    "number": 3
  },
  {
    "name": "Jared Harper",
    "team": "Hapoel Jerusalem",
    "nationality": "USA",
    "position": "Guard",
    "height": 178,
    "birthYear": 1997,
    "number": 1
  },
  {
    "name": "Shake Milton",
    "team": "Hapoel Jerusalem",
    "nationality": "USA",
    "position": "Guard",
    "height": 196,
    "birthYear": 1996,
    "number": 9
  },
  {
    "name": "Adrian Nelson",
    "team": "JL Bourg-en-Bresse",
    "nationality": "USA",
    "position": "Forward",
    "height": 203,
    "birthYear": 1999,
    "number": 4
  },
  {
    "name": "Antony Labanca",
    "team": "JL Bourg-en-Bresse",
    "nationality": "France",
    "position": "Guard",
    "height": 192,
    "birthYear": 1994,
    "number": 8
  },
  {
    "name": "Assemian Moulare",
    "team": "JL Bourg-en-Bresse",
    "nationality": "Ivory Coast",
    "position": "Guard",
    "height": 186,
    "birthYear": 2003,
    "number": 3
  },
  {
    "name": "Hugo Robineau",
    "team": "JL Bourg-en-Bresse",
    "nationality": "France",
    "position": "Guard",
    "height": 192,
    "birthYear": 2000,
    "number": 87
  },
  {
    "name": "Kadin Shedrick",
    "team": "JL Bourg-en-Bresse",
    "nationality": "USA",
    "position": "Center",
    "height": 211,
    "birthYear": 2001,
    "number": 21
  },
  {
    "name": "Keith Jordan Jr.",
    "team": "JL Bourg-en-Bresse",
    "nationality": "USA",
    "position": "Guard",
    "height": 198,
    "birthYear": 1998,
    "number": 2
  },
  {
    "name": "Leni Monnet",
    "team": "JL Bourg-en-Bresse",
    "nationality": "France",
    "position": "Guard",
    "height": 194,
    "birthYear": 2006,
    "number": 55
  },
  {
    "name": "Lionel Gaudoux",
    "team": "JL Bourg-en-Bresse",
    "nationality": "France",
    "position": "Center",
    "height": 198,
    "birthYear": 1995,
    "number": 13
  },
  {
    "name": "Trey Woodbury",
    "team": "JL Bourg-en-Bresse",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1999,
    "number": 22
  },
  {
    "name": "Tyrese Samuel",
    "team": "JL Bourg-en-Bresse",
    "nationality": "Canada",
    "position": "Forward",
    "height": 206,
    "birthYear": 2000,
    "number": 5
  },
  {
    "name": "Tyson Walker",
    "team": "JL Bourg-en-Bresse",
    "nationality": "USA",
    "position": "Guard",
    "height": 185,
    "birthYear": 2000,
    "number": 12
  },
  {
    "name": "Xabier Lopez-Arostegui",
    "team": "La Laguna Tenerife",
    "nationality": "Spain",
    "position": "Forward",
    "height": 200,
    "birthYear": 1997,
    "number": 7
  },
  {
    "name": "Melvin Ajinca",
    "team": "Le Mans",
    "nationality": "France",
    "position": "Forward",
    "height": 202,
    "birthYear": 2004,
    "number": 8
  },
  {
    "name": "Rafa Villar",
    "team": "Manresa",
    "nationality": "Spain",
    "position": "Guard",
    "height": 191,
    "birthYear": 2004,
    "number": 44
  },
  {
    "name": "Jeffrey Dowtin Jr.",
    "team": "Napoli Basketball",
    "nationality": "USA",
    "position": "Guard",
    "height": 191,
    "birthYear": 1997,
    "number": 3
  },
  {
    "name": "Zac Seljaas",
    "team": "Napoli Basketball",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1997,
    "number": 1
  },
  {
    "name": "Cedi Osman",
    "team": "PAOK",
    "nationality": "Turkey",
    "position": "Forward",
    "height": 207,
    "birthYear": 1995,
    "number": 6
  },
  {
    "name": "Nick Calathes",
    "team": "PAOK",
    "nationality": "USA",
    "position": "Guard",
    "height": 198,
    "birthYear": 1989,
    "number": 33
  },
  {
    "name": "Armel Traore",
    "team": "Ratiopharm Ulm",
    "nationality": "France",
    "position": "Forward",
    "height": 205,
    "birthYear": 2003,
    "number": 94
  },
  {
    "name": "Glynn Watson Jr.",
    "team": "Reyer Venezia",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 1997,
    "number": 30
  },
  {
    "name": "Nico Mannion",
    "team": "Roma Basketball",
    "nationality": "Italy",
    "position": "Guard",
    "height": 188,
    "birthYear": 2001,
    "number": 1
  },
  {
    "name": "Alessandro Bertini",
    "team": "Trento",
    "nationality": "Italy",
    "position": "Forward",
    "height": 195,
    "birthYear": 2002,
    "number": 5
  },
  {
    "name": "Charlie Brown Jr.",
    "team": "Trento",
    "nationality": "USA",
    "position": "Forward",
    "height": 198,
    "birthYear": 1997,
    "number": 4
  },
  {
    "name": "Darius Brown II",
    "team": "Trento",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 1999,
    "number": 0
  },
  {
    "name": "Isaiah Bigelow",
    "team": "Trento",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 2000,
    "number": 24
  },
  {
    "name": "Jordan Bayehe",
    "team": "Trento",
    "nationality": "Cameroon",
    "position": "Center",
    "height": 206,
    "birthYear": 1999,
    "number": 26
  },
  {
    "name": "Quincy Olivari",
    "team": "Trento",
    "nationality": "USA",
    "position": "Guard",
    "height": 191,
    "birthYear": 2001,
    "number": 8
  },
  {
    "name": "Selom Mawugbe",
    "team": "Trento",
    "nationality": "USA",
    "position": "Center",
    "height": 208,
    "birthYear": 1998,
    "number": 21
  },
  {
    "name": "Toto Forray",
    "team": "Trento",
    "nationality": "Argentina",
    "position": "Guard",
    "height": 187,
    "birthYear": 1986,
    "number": 10
  },
  {
    "name": "Shaquielle McKissic",
    "team": "Turk Telekom",
    "nationality": "USA",
    "position": "Forward",
    "height": 196,
    "birthYear": 1990,
    "number": 77
  }
];
