/*
 * EuroCup 2026-27 player database (auto-generated by build_eurocup.js — do not edit).
 * Same record shape as players.js. Until EUROCUP_OPEN is true the EuroCup stays
 * a coming-soon page.
 */

window.EUROCUP_OPEN = false;

window.EUROCUP_TEAMS = {
  "Aris Thessaloniki": {
    "country": "Greece"
  },
  "Derthona Tortona": {
    "country": "Italy"
  },
  "Bahcesehir College": {
    "country": "Turkey"
  },
  "Balkan Botevgrad": {
    "country": "Bulgaria"
  },
  "Bosna Sarajevo": {
    "country": "Bosnia and Herzegovina"
  },
  "Buducnost": {
    "country": "Montenegro"
  },
  "Cedevita Olimpija": {
    "country": "Slovenia"
  },
  "JL Bourg-en-Bresse": {
    "country": "France"
  },
  "Trento": {
    "country": "Italy"
  },
  "Hapoel Jerusalem": {
    "country": "Israel"
  },
  "Manresa": {
    "country": "Spain"
  },
  "La Laguna Tenerife": {
    "country": "Spain"
  },
  "Le Mans": {
    "country": "France"
  },
  "Lietkabelis": {
    "country": "Lithuania"
  },
  "London Lions": {
    "country": "United Kingdom"
  },
  "Maxima Roma": {
    "country": "Italy"
  },
  "Napoli Basketball": {
    "country": "Italy"
  },
  "Neptunas": {
    "country": "Lithuania"
  },
  "Niners Chemnitz": {
    "country": "Germany"
  },
  "PAOK": {
    "country": "Greece"
  },
  "Ratiopharm Ulm": {
    "country": "Germany"
  },
  "San Pablo Burgos": {
    "country": "Spain"
  },
  "Riga Zelli": {
    "country": "Latvia"
  },
  "Roma Basketball": {
    "country": "Italy"
  },
  "Rostock Seawolves": {
    "country": "Germany"
  },
  "Siauliai": {
    "country": "Lithuania"
  },
  "Skyliners Frankfurt": {
    "country": "Germany"
  },
  "Slask Wroclaw": {
    "country": "Poland"
  },
  "Tofas": {
    "country": "Turkey"
  },
  "Turk Telekom": {
    "country": "Turkey"
  },
  "Cluj-Napoca": {
    "country": "Romania"
  },
  "Reyer Venezia": {
    "country": "Italy"
  }
};

window.EUROCUP_PLAYERS = [
  {
    "name": "Adam Mokoka",
    "team": "Aris Thessaloniki",
    "nationality": "France",
    "position": "Forward",
    "height": 196,
    "birthYear": 1998,
    "number": 95
  },
  {
    "name": "E.J. Liddell",
    "team": "Aris Thessaloniki",
    "nationality": "USA",
    "position": "Forward",
    "height": 198,
    "birthYear": 2000,
    "number": 32
  },
  {
    "name": "Eleftherios Bochoridis",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Guard",
    "height": 196,
    "birthYear": 1994,
    "number": 13
  },
  {
    "name": "Elijah Mitrou-Long",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Guard",
    "height": 187,
    "birthYear": 1996,
    "number": 0
  },
  {
    "name": "Georgios Tanoulis",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Center",
    "height": 210,
    "birthYear": 2002,
    "number": 50
  },
  {
    "name": "Jeremiah Robinson-Earl",
    "team": "Aris Thessaloniki",
    "nationality": "USA",
    "position": "Forward",
    "height": 206,
    "birthYear": 2000,
    "number": 3
  },
  {
    "name": "Khem Birch",
    "team": "Aris Thessaloniki",
    "nationality": "Canada",
    "position": "Center",
    "height": 206,
    "birthYear": 1992,
    "number": 92
  },
  {
    "name": "Kostas Antetokounmpo",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Center",
    "height": 208,
    "birthYear": 1997,
    "number": 37
  },
  {
    "name": "Matt Morgan",
    "team": "Aris Thessaloniki",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1997,
    "number": 30
  },
  {
    "name": "Neno Dimitrijevic",
    "team": "Aris Thessaloniki",
    "nationality": "North Macedonia",
    "position": "Guard",
    "height": 190,
    "birthYear": 1998,
    "number": 7
  },
  {
    "name": "Stefan Jovic",
    "team": "Aris Thessaloniki",
    "nationality": "Serbia",
    "position": "Guard",
    "height": 198,
    "birthYear": 1990,
    "number": 24
  },
  {
    "name": "Stylianos Poulianitis",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Guard",
    "height": 190,
    "birthYear": 1995,
    "number": 11
  },
  {
    "name": "Thanasis Antetokounmpo",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Forward",
    "height": 201,
    "birthYear": 1992,
    "number": 43
  },
  {
    "name": "Vasilis Charalampopoulos",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Forward",
    "height": 204,
    "birthYear": 1997,
    "number": 33
  },
  {
    "name": "Vassilis Toliopoulos",
    "team": "Aris Thessaloniki",
    "nationality": "Greece",
    "position": "Guard",
    "height": 188,
    "birthYear": 1996,
    "number": 4
  },
  {
    "name": "Aleksa Avramovic",
    "team": "Bahcesehir College",
    "nationality": "Serbia",
    "position": "Guard",
    "height": 193,
    "birthYear": 1994,
    "number": 4
  },
  {
    "name": "Damien Inglis",
    "team": "Bahcesehir College",
    "nationality": "France",
    "position": "Center",
    "height": 203,
    "birthYear": 1995,
    "number": 7
  },
  {
    "name": "David DiLeo",
    "team": "Bahcesehir College",
    "nationality": "USA",
    "position": "Forward",
    "height": 203,
    "birthYear": 1997,
    "number": 51
  },
  {
    "name": "Furkan Haltali",
    "team": "Bahcesehir College",
    "nationality": "Turkey",
    "position": "Center",
    "height": 211,
    "birthYear": 2002,
    "number": 14
  },
  {
    "name": "Isiaha Mike",
    "team": "Bahcesehir College",
    "nationality": "Canada",
    "position": "Forward",
    "height": 203,
    "birthYear": 1997,
    "number": 24
  },
  {
    "name": "Ismet Akpinar",
    "team": "Bahcesehir College",
    "nationality": "Germany",
    "position": "Guard",
    "height": 191,
    "birthYear": 1995,
    "number": 5
  },
  {
    "name": "Kenan Sipahi",
    "team": "Bahcesehir College",
    "nationality": "Turkey",
    "position": "Guard",
    "height": 197,
    "birthYear": 1995,
    "number": 55
  },
  {
    "name": "Malachi Flynn",
    "team": "Bahcesehir College",
    "nationality": "Turkey",
    "position": "Guard",
    "height": 185,
    "birthYear": 1998,
    "number": 22
  },
  {
    "name": "Marcquise Reed",
    "team": "Bahcesehir College",
    "nationality": "Georgia",
    "position": "Guard",
    "height": 191,
    "birthYear": 1995,
    "number": 0
  },
  {
    "name": "Mateusz Ponitka",
    "team": "Bahcesehir College",
    "nationality": "Poland",
    "position": "Forward",
    "height": 198,
    "birthYear": 1993,
    "number": 38
  },
  {
    "name": "Maxim Mutaf",
    "team": "Bahcesehir College",
    "nationality": "Turkey",
    "position": "Forward",
    "height": 193,
    "birthYear": 1991,
    "number": 17
  },
  {
    "name": "Trevion Williams",
    "team": "Bahcesehir College",
    "nationality": "USA",
    "position": "Center",
    "height": 206,
    "birthYear": 2000,
    "number": 50
  },
  {
    "name": "Tyler Cavanaugh",
    "team": "Bahcesehir College",
    "nationality": "USA",
    "position": "Forward",
    "height": 206,
    "birthYear": 1994,
    "number": 34
  },
  {
    "name": "Aleksandar Stoimenov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Guard",
    "height": 198,
    "birthYear": 2001,
    "number": 3
  },
  {
    "name": "Alex Ducas",
    "team": "Balkan Botevgrad",
    "nationality": "Australia",
    "position": "Forward",
    "height": 201,
    "birthYear": 2000,
    "number": 8
  },
  {
    "name": "Darnell Edge",
    "team": "Balkan Botevgrad",
    "nationality": "USA",
    "position": "Guard",
    "height": 185,
    "birthYear": 1997,
    "number": 1
  },
  {
    "name": "David Okwera",
    "team": "Balkan Botevgrad",
    "nationality": "Australia",
    "position": "Forward",
    "height": 208,
    "birthYear": 2002,
    "number": 0
  },
  {
    "name": "Dimitar Dimitrov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Forward",
    "height": 203,
    "birthYear": 1993,
    "number": 34
  },
  {
    "name": "Gael Bonilla",
    "team": "Balkan Botevgrad",
    "nationality": "Mexico",
    "position": "Forward",
    "height": 203,
    "birthYear": 2003,
    "number": 2
  },
  {
    "name": "Ivan Alipiev",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Forward",
    "height": 200,
    "birthYear": 1999,
    "number": 35
  },
  {
    "name": "Ivan Spirov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Forward",
    "height": 203,
    "birthYear": 2003,
    "number": 91
  },
  {
    "name": "Javante McCoy",
    "team": "Balkan Botevgrad",
    "nationality": "USA",
    "position": "Guard",
    "height": 196,
    "birthYear": 1998,
    "number": 13
  },
  {
    "name": "Konstantin Toshkov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Guard",
    "height": 186,
    "birthYear": 2002,
    "number": 22
  },
  {
    "name": "Martin Sotirov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Forward",
    "height": 201,
    "birthYear": 1999,
    "number": 44
  },
  {
    "name": "Nikolay Grozev",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Forward",
    "height": 198,
    "birthYear": 1994,
    "number": 33
  },
  {
    "name": "Pavlin Ivanov",
    "team": "Balkan Botevgrad",
    "nationality": "Bulgaria",
    "position": "Guard",
    "height": 196,
    "birthYear": 1993,
    "number": 10
  },
  {
    "name": "Ulrich Chomche",
    "team": "Balkan Botevgrad",
    "nationality": "Cameroon",
    "position": "Center",
    "height": 211,
    "birthYear": 2005,
    "number": 14
  },
  {
    "name": "Adin Vrabac",
    "team": "Bosna Sarajevo",
    "nationality": "Bosnia and Herzegovina",
    "position": "Guard",
    "height": 206,
    "birthYear": 1994,
    "number": 7
  },
  {
    "name": "Alija Islamovic",
    "team": "Bosna Sarajevo",
    "nationality": "Bosnia and Herzegovina",
    "position": "Center",
    "height": 207,
    "birthYear": 2001,
    "number": 33
  },
  {
    "name": "Darko Talic",
    "team": "Bosna Sarajevo",
    "nationality": "Bosnia and Herzegovina",
    "position": "Guard",
    "height": 192,
    "birthYear": 1998,
    "number": 19
  },
  {
    "name": "DeAndre Gholston",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Guard",
    "height": 196,
    "birthYear": 2000,
    "number": 4
  },
  {
    "name": "Edin Atic",
    "team": "Bosna Sarajevo",
    "nationality": "Bosnia and Herzegovina",
    "position": "Guard",
    "height": 201,
    "birthYear": 1997,
    "number": 5
  },
  {
    "name": "Gary Browne",
    "team": "Bosna Sarajevo",
    "nationality": "Puerto Rico",
    "position": "Guard",
    "height": 185,
    "birthYear": 1993,
    "number": 14
  },
  {
    "name": "James Banks",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Center",
    "height": 208,
    "birthYear": 1998,
    "number": 1
  },
  {
    "name": "Marcus Domask",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Guard",
    "height": 198,
    "birthYear": 2000,
    "number": 3
  },
  {
    "name": "Nikola Popovic",
    "team": "Bosna Sarajevo",
    "nationality": "Serbia",
    "position": "Center",
    "height": 211,
    "birthYear": 1997,
    "number": 21
  },
  {
    "name": "Reginald Perry",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Center",
    "height": 203,
    "birthYear": 2000,
    "number": 11
  },
  {
    "name": "Ryan Hawkins",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1997,
    "number": 44
  },
  {
    "name": "Shawn Pipes Jr.",
    "team": "Bosna Sarajevo",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 1999,
    "number": 2
  },
  {
    "name": "Andrija Slavkovic",
    "team": "Buducnost",
    "nationality": "Montenegro",
    "position": "Forward",
    "height": 201,
    "birthYear": 1999,
    "number": 7
  },
  {
    "name": "Axel Bouteille",
    "team": "Buducnost",
    "nationality": "France",
    "position": "Forward",
    "height": 201,
    "birthYear": 1995,
    "number": 83
  },
  {
    "name": "Dordije Jovanovic",
    "team": "Buducnost",
    "nationality": "Montenegro",
    "position": "Forward",
    "height": 197,
    "birthYear": 2003,
    "number": 13
  },
  {
    "name": "Emir Hadzibegovic",
    "team": "Buducnost",
    "nationality": "Montenegro",
    "position": "Forward",
    "height": 206,
    "birthYear": 1996,
    "number": 8
  },
  {
    "name": "Fletcher Magee",
    "team": "Buducnost",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1996,
    "number": 3
  },
  {
    "name": "Iverson Molinar",
    "team": "Buducnost",
    "nationality": "Panama",
    "position": "Guard",
    "height": 191,
    "birthYear": 1999,
    "number": 10
  },
  {
    "name": "Jerry Boutsiele",
    "team": "Buducnost",
    "nationality": "France",
    "position": "Center",
    "height": 208,
    "birthYear": 1992,
    "number": 16
  },
  {
    "name": "Justin Smith",
    "team": "Buducnost",
    "nationality": "USA",
    "position": "Center",
    "height": 201,
    "birthYear": 1999,
    "number": 0
  },
  {
    "name": "Juwan Morgan",
    "team": "Buducnost",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1997,
    "number": 15
  },
  {
    "name": "Marial Shayok",
    "team": "Buducnost",
    "nationality": "South Sudan",
    "position": "Forward",
    "height": 196,
    "birthYear": 1995,
    "number": 1
  },
  {
    "name": "Oleksandr Kovliar",
    "team": "Buducnost",
    "nationality": "Ukraine",
    "position": "Forward",
    "height": 191,
    "birthYear": 2002,
    "number": 50
  },
  {
    "name": "Stefan Dordevic",
    "team": "Buducnost",
    "nationality": "Serbia",
    "position": "Center",
    "height": 206,
    "birthYear": 1998,
    "number": 45
  },
  {
    "name": "Yogi Ferrell",
    "team": "Buducnost",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 1993,
    "number": 11
  },
  {
    "name": "Anthony Cowan Jr.",
    "team": "Cedevita Olimpija",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 1997,
    "number": 1
  },
  {
    "name": "David Skara",
    "team": "Cedevita Olimpija",
    "nationality": "Croatia",
    "position": "Center",
    "height": 203,
    "birthYear": 1995,
    "number": 24
  },
  {
    "name": "Jaka Blazic",
    "team": "Cedevita Olimpija",
    "nationality": "Slovenia",
    "position": "Guard",
    "height": 196,
    "birthYear": 1990,
    "number": 11
  },
  {
    "name": "Jayce Johnson",
    "team": "Cedevita Olimpija",
    "nationality": "USA",
    "position": "Center",
    "height": 213,
    "birthYear": 1997,
    "number": 34
  },
  {
    "name": "Jordan Gainey",
    "team": "Cedevita Olimpija",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 2002,
    "number": 4
  },
  {
    "name": "Matthew Hurt",
    "team": "Cedevita Olimpija",
    "nationality": "USA",
    "position": "Forward",
    "height": 206,
    "birthYear": 2000,
    "number": 21
  },
  {
    "name": "Miha Cerkvenik",
    "team": "Cedevita Olimpija",
    "nationality": "Slovenia",
    "position": "Forward",
    "height": 201,
    "birthYear": 2001,
    "number": 20
  },
  {
    "name": "Noah Kirkwood",
    "team": "Cedevita Olimpija",
    "nationality": "Canada",
    "position": "Forward",
    "height": 201,
    "birthYear": 1999,
    "number": 22
  },
  {
    "name": "Osayi Osifo",
    "team": "Cedevita Olimpija",
    "nationality": "South Africa",
    "position": "Center",
    "height": 206,
    "birthYear": 2000,
    "number": 14
  },
  {
    "name": "Rihards Lomazs",
    "team": "Cedevita Olimpija",
    "nationality": "Latvia",
    "position": "Guard",
    "height": 193,
    "birthYear": 1996,
    "number": 6
  },
  {
    "name": "Rok Radovic",
    "team": "Cedevita Olimpija",
    "nationality": "Slovenia",
    "position": "Forward",
    "height": 201,
    "birthYear": 2001,
    "number": 3
  },
  {
    "name": "Urban Kroflic",
    "team": "Cedevita Olimpija",
    "nationality": "Slovenia",
    "position": "Guard",
    "height": 198,
    "birthYear": 2006,
    "number": 23
  },
  {
    "name": "Bobe Nicolescu",
    "team": "Cluj-Napoca",
    "nationality": "Romania",
    "position": "Forward",
    "height": 199,
    "birthYear": 1997,
    "number": 24
  },
  {
    "name": "Christian Bishop",
    "team": "Cluj-Napoca",
    "nationality": "USA",
    "position": "Center",
    "height": 200,
    "birthYear": 2000,
    "number": 13
  },
  {
    "name": "Dusan Beslac",
    "team": "Cluj-Napoca",
    "nationality": "Serbia",
    "position": "Forward",
    "height": 204,
    "birthYear": 1998,
    "number": 3
  },
  {
    "name": "Jalyn McCreary",
    "team": "Cluj-Napoca",
    "nationality": "USA",
    "position": "Forward",
    "height": 202,
    "birthYear": 2000,
    "number": 8
  },
  {
    "name": "Javon Bess",
    "team": "Cluj-Napoca",
    "nationality": "USA",
    "position": "Forward",
    "height": 195,
    "birthYear": 1996,
    "number": 20
  },
  {
    "name": "Javonte Smart",
    "team": "Cluj-Napoca",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1999,
    "number": 1
  },
  {
    "name": "Kristian Kullamae",
    "team": "Cluj-Napoca",
    "nationality": "Estonia",
    "position": "Guard",
    "height": 194,
    "birthYear": 1999,
    "number": 77
  },
  {
    "name": "Malcolm Hill",
    "team": "Cluj-Napoca",
    "nationality": "USA",
    "position": "Guard",
    "height": 197,
    "birthYear": 1995,
    "number": 21
  },
  {
    "name": "Otis Livingston II",
    "team": "Cluj-Napoca",
    "nationality": "USA",
    "position": "Guard",
    "height": 177,
    "birthYear": 1996,
    "number": 0
  },
  {
    "name": "Patrick Richard",
    "team": "Cluj-Napoca",
    "nationality": "Romania",
    "position": "Guard",
    "height": 194,
    "birthYear": 1990,
    "number": 35
  },
  {
    "name": "Uros Plavsic",
    "team": "Cluj-Napoca",
    "nationality": "Serbia",
    "position": "Center",
    "height": 215,
    "birthYear": 1998,
    "number": 22
  },
  {
    "name": "Aljami Durham",
    "team": "Derthona Tortona",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1998,
    "number": 42
  },
  {
    "name": "Amar Alibegovic",
    "team": "Derthona Tortona",
    "nationality": "Bosnia and Herzegovina",
    "position": "Forward",
    "height": 206,
    "birthYear": 1995,
    "number": 7
  },
  {
    "name": "Andrea Pecchia",
    "team": "Derthona Tortona",
    "nationality": "Italy",
    "position": "Guard",
    "height": 196,
    "birthYear": 1997,
    "number": 6
  },
  {
    "name": "Dante Maddox Jr.",
    "team": "Derthona Tortona",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 2002,
    "number": 21
  },
  {
    "name": "Dominik Olejniczak",
    "team": "Derthona Tortona",
    "nationality": "Poland",
    "position": "Center",
    "height": 213,
    "birthYear": 1996,
    "number": 17
  },
  {
    "name": "Giordano Bortolani",
    "team": "Derthona Tortona",
    "nationality": "Italy",
    "position": "Guard",
    "height": 193,
    "birthYear": 2000,
    "number": 12
  },
  {
    "name": "Giulio Gazzotti",
    "team": "Derthona Tortona",
    "nationality": "Italy",
    "position": "Forward",
    "height": 203,
    "birthYear": 1991,
    "number": 24
  },
  {
    "name": "Justin Gorham",
    "team": "Derthona Tortona",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1998,
    "number": 4
  },
  {
    "name": "Karim Jallow",
    "team": "Derthona Tortona",
    "nationality": "Germany",
    "position": "Forward",
    "height": 198,
    "birthYear": 1997,
    "number": 35
  },
  {
    "name": "Paul Eboua",
    "team": "Derthona Tortona",
    "nationality": "Cameroon",
    "position": "Forward",
    "height": 203,
    "birthYear": 2000,
    "number": 0
  },
  {
    "name": "Prentiss Hubb",
    "team": "Derthona Tortona",
    "nationality": "USA",
    "position": "Guard",
    "height": 191,
    "birthYear": 1999,
    "number": 3
  },
  {
    "name": "David Roddy",
    "team": "Hapoel Jerusalem",
    "nationality": "USA",
    "position": "Forward",
    "height": 196,
    "birthYear": 2001,
    "number": 21
  },
  {
    "name": "DeVontae Cacok",
    "team": "Hapoel Jerusalem",
    "nationality": "USA",
    "position": "Center",
    "height": 201,
    "birthYear": 1996,
    "number": 0
  },
  {
    "name": "Dusan Miletic",
    "team": "Hapoel Jerusalem",
    "nationality": "Serbia",
    "position": "Center",
    "height": 215,
    "birthYear": 1998,
    "number": 11
  },
  {
    "name": "Ethan Burg",
    "team": "Hapoel Jerusalem",
    "nationality": "Israel",
    "position": "Guard",
    "height": 191,
    "birthYear": 2002,
    "number": 35
  },
  {
    "name": "Gabriel Chachashvili",
    "team": "Hapoel Jerusalem",
    "nationality": "Israel",
    "position": "Center",
    "height": 210,
    "birthYear": 1999,
    "number": 33
  },
  {
    "name": "Jaleen Smith",
    "team": "Hapoel Jerusalem",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1994,
    "number": 3
  },
  {
    "name": "Jared Harper",
    "team": "Hapoel Jerusalem",
    "nationality": "USA",
    "position": "Guard",
    "height": 178,
    "birthYear": 1997,
    "number": 1
  },
  {
    "name": "Kenny Lofton Jr.",
    "team": "Hapoel Jerusalem",
    "nationality": "USA",
    "position": "Forward",
    "height": 198,
    "birthYear": 2002,
    "number": 2
  },
  {
    "name": "Nimrod Levi",
    "team": "Hapoel Jerusalem",
    "nationality": "Israel",
    "position": "Forward",
    "height": 208,
    "birthYear": 1995,
    "number": 15
  },
  {
    "name": "Roi Huber",
    "team": "Hapoel Jerusalem",
    "nationality": "Israel",
    "position": "Guard",
    "height": 188,
    "birthYear": 1997,
    "number": 13
  },
  {
    "name": "Shake Milton",
    "team": "Hapoel Jerusalem",
    "nationality": "USA",
    "position": "Guard",
    "height": 196,
    "birthYear": 1996,
    "number": 9
  },
  {
    "name": "Yotam Hanochi",
    "team": "Hapoel Jerusalem",
    "nationality": "Israel",
    "position": "Center",
    "height": 208,
    "birthYear": 2000,
    "number": 8
  },
  {
    "name": "Yovel Zoosman",
    "team": "Hapoel Jerusalem",
    "nationality": "Israel",
    "position": "Guard",
    "height": 200,
    "birthYear": 1998,
    "number": 50
  },
  {
    "name": "Adrian Nelson",
    "team": "JL Bourg-en-Bresse",
    "nationality": "USA",
    "position": "Forward",
    "height": 203,
    "birthYear": 1999,
    "number": 4
  },
  {
    "name": "Antony Labanca",
    "team": "JL Bourg-en-Bresse",
    "nationality": "France",
    "position": "Guard",
    "height": 192,
    "birthYear": 1994,
    "number": 8
  },
  {
    "name": "Assemian Moulare",
    "team": "JL Bourg-en-Bresse",
    "nationality": "Ivory Coast",
    "position": "Guard",
    "height": 186,
    "birthYear": 2003,
    "number": 3
  },
  {
    "name": "Hugo Robineau",
    "team": "JL Bourg-en-Bresse",
    "nationality": "France",
    "position": "Guard",
    "height": 192,
    "birthYear": 2000,
    "number": 87
  },
  {
    "name": "Kadin Shedrick",
    "team": "JL Bourg-en-Bresse",
    "nationality": "USA",
    "position": "Center",
    "height": 211,
    "birthYear": 2001,
    "number": 21
  },
  {
    "name": "Keith Jordan Jr.",
    "team": "JL Bourg-en-Bresse",
    "nationality": "USA",
    "position": "Guard",
    "height": 198,
    "birthYear": 1998,
    "number": 2
  },
  {
    "name": "Leni Monnet",
    "team": "JL Bourg-en-Bresse",
    "nationality": "France",
    "position": "Guard",
    "height": 194,
    "birthYear": 2006,
    "number": 55
  },
  {
    "name": "Lionel Gaudoux",
    "team": "JL Bourg-en-Bresse",
    "nationality": "France",
    "position": "Center",
    "height": 198,
    "birthYear": 1995,
    "number": 13
  },
  {
    "name": "Trey Woodbury",
    "team": "JL Bourg-en-Bresse",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1999,
    "number": 22
  },
  {
    "name": "Tyrese Samuel",
    "team": "JL Bourg-en-Bresse",
    "nationality": "Canada",
    "position": "Forward",
    "height": 206,
    "birthYear": 2000,
    "number": 5
  },
  {
    "name": "Tyson Walker",
    "team": "JL Bourg-en-Bresse",
    "nationality": "USA",
    "position": "Guard",
    "height": 185,
    "birthYear": 2000,
    "number": 12
  },
  {
    "name": "Arturs Kurucs",
    "team": "La Laguna Tenerife",
    "nationality": "Latvia",
    "position": "Guard",
    "height": 193,
    "birthYear": 2000,
    "number": 47
  },
  {
    "name": "Bamba Cisse",
    "team": "La Laguna Tenerife",
    "nationality": "USA",
    "position": "Forward",
    "height": 196,
    "birthYear": 2001,
    "number": 1
  },
  {
    "name": "Bruno Fitipaldo",
    "team": "La Laguna Tenerife",
    "nationality": "Uruguay",
    "position": "Guard",
    "height": 184,
    "birthYear": 1991,
    "number": 6
  },
  {
    "name": "Ethan Happ",
    "team": "La Laguna Tenerife",
    "nationality": "USA",
    "position": "Center",
    "height": 208,
    "birthYear": 1996,
    "number": 22
  },
  {
    "name": "Hector Alderete",
    "team": "La Laguna Tenerife",
    "nationality": "Spain",
    "position": "Forward",
    "height": 203,
    "birthYear": 2002,
    "number": 33
  },
  {
    "name": "Jaime Fernandez",
    "team": "La Laguna Tenerife",
    "nationality": "Spain",
    "position": "Guard",
    "height": 186,
    "birthYear": 1993,
    "number": 3
  },
  {
    "name": "Kyle Guy",
    "team": "La Laguna Tenerife",
    "nationality": "USA",
    "position": "Forward",
    "height": 185,
    "birthYear": 1997,
    "number": 2
  },
  {
    "name": "Marcelinho Huertas",
    "team": "La Laguna Tenerife",
    "nationality": "Brazil",
    "position": "Guard",
    "height": 191,
    "birthYear": 1983,
    "number": 9
  },
  {
    "name": "Tim Abromaitis",
    "team": "La Laguna Tenerife",
    "nationality": "USA",
    "position": "Center",
    "height": 203,
    "birthYear": 1989,
    "number": 21
  },
  {
    "name": "Vince Hunter",
    "team": "La Laguna Tenerife",
    "nationality": "USA",
    "position": "Center",
    "height": 203,
    "birthYear": 1994,
    "number": 32
  },
  {
    "name": "Wesley van Beck",
    "team": "La Laguna Tenerife",
    "nationality": "Azerbaijan",
    "position": "Forward",
    "height": 193,
    "birthYear": 1996,
    "number": 4
  },
  {
    "name": "Xabier Lopez-Arostegui",
    "team": "La Laguna Tenerife",
    "nationality": "Spain",
    "position": "Forward",
    "height": 200,
    "birthYear": 1997,
    "number": 7
  },
  {
    "name": "Carlos Stewart Jr.",
    "team": "Le Mans",
    "nationality": "USA",
    "position": "Guard",
    "height": 185,
    "birthYear": 2003,
    "number": 0
  },
  {
    "name": "Jordan King",
    "team": "Le Mans",
    "nationality": "Jamaica",
    "position": "Guard",
    "height": 183,
    "birthYear": 2001,
    "number": 2
  },
  {
    "name": "Leopold Delaunay",
    "team": "Le Mans",
    "nationality": "France",
    "position": "Guard",
    "height": 193,
    "birthYear": 2001,
    "number": 9
  },
  {
    "name": "Lucas Dufeal",
    "team": "Le Mans",
    "nationality": "France",
    "position": "Forward",
    "height": 204,
    "birthYear": 2003,
    "number": 32
  },
  {
    "name": "Melvin Ajinca",
    "team": "Le Mans",
    "nationality": "France",
    "position": "Forward",
    "height": 202,
    "birthYear": 2004,
    "number": 8
  },
  {
    "name": "Moses Wood",
    "team": "Le Mans",
    "nationality": "USA",
    "position": "Forward",
    "height": 203,
    "birthYear": 1999,
    "number": 23
  },
  {
    "name": "Tashawn Thomas",
    "team": "Le Mans",
    "nationality": "USA",
    "position": "Center",
    "height": 203,
    "birthYear": 1993,
    "number": 35
  },
  {
    "name": "Tyler Beracou",
    "team": "Le Mans",
    "nationality": "France",
    "position": "Center",
    "height": 202,
    "birthYear": 2006,
    "number": 26
  },
  {
    "name": "Ugo Doumbia Niang",
    "team": "Le Mans",
    "nationality": "France",
    "position": "Guard",
    "height": 193,
    "birthYear": 2003,
    "number": 10
  },
  {
    "name": "Wilfried Yeguete",
    "team": "Le Mans",
    "nationality": "France",
    "position": "Center",
    "height": 202,
    "birthYear": 1991,
    "number": 15
  },
  {
    "name": "Alexander Schumacher",
    "team": "Lietkabelis",
    "nationality": "Switzerland",
    "position": "Guard",
    "height": 190,
    "birthYear": 2001,
    "number": 2
  },
  {
    "name": "Daniel Baslyk",
    "team": "Lietkabelis",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 198,
    "birthYear": 2001,
    "number": 9
  },
  {
    "name": "Gabrielius Maldunas",
    "team": "Lietkabelis",
    "nationality": "Lithuania",
    "position": "Center",
    "height": 206,
    "birthYear": 1993,
    "number": 12
  },
  {
    "name": "Gytis Nemeiksa",
    "team": "Lietkabelis",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 201,
    "birthYear": 2001,
    "number": 50
  },
  {
    "name": "Ivan Fevrier",
    "team": "Lietkabelis",
    "nationality": "France",
    "position": "Forward",
    "height": 205,
    "birthYear": 1999,
    "number": 23
  },
  {
    "name": "Keondre Kennedy",
    "team": "Lietkabelis",
    "nationality": "USA",
    "position": "Forward",
    "height": 198,
    "birthYear": 2000,
    "number": 0
  },
  {
    "name": "Marius Valinskas",
    "team": "Lietkabelis",
    "nationality": "Lithuania",
    "position": "Guard",
    "height": 189,
    "birthYear": 1999,
    "number": 99
  },
  {
    "name": "Milos Ilic",
    "team": "Lietkabelis",
    "nationality": "Serbia",
    "position": "Forward",
    "height": 205,
    "birthYear": 2002,
    "number": 11
  },
  {
    "name": "Nojus Radzius",
    "team": "Lietkabelis",
    "nationality": "Lithuania",
    "position": "Guard",
    "height": 184,
    "birthYear": 2005,
    "number": 5
  },
  {
    "name": "Ognjen Jaramaz",
    "team": "Lietkabelis",
    "nationality": "Serbia",
    "position": "Guard",
    "height": 193,
    "birthYear": 1995,
    "number": 10
  },
  {
    "name": "Veljko Ilic",
    "team": "Lietkabelis",
    "nationality": "Serbia",
    "position": "Center",
    "height": 208,
    "birthYear": 2002,
    "number": 8
  },
  {
    "name": "Zygimantas Simonis",
    "team": "Lietkabelis",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 194,
    "birthYear": 1995,
    "number": 3
  },
  {
    "name": "Aaryn Rai",
    "team": "London Lions",
    "nationality": "United Kingdom",
    "position": "Forward",
    "height": 197,
    "birthYear": 1998,
    "number": 21
  },
  {
    "name": "Deane Williams",
    "team": "London Lions",
    "nationality": "United Kingdom",
    "position": "Forward",
    "height": 203,
    "birthYear": 1996,
    "number": 31
  },
  {
    "name": "Devante Jones",
    "team": "London Lions",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 1998,
    "number": 3
  },
  {
    "name": "Ethan Price",
    "team": "London Lions",
    "nationality": "United Kingdom",
    "position": "Forward",
    "height": 206,
    "birthYear": 2001,
    "number": 10
  },
  {
    "name": "Joel Scott",
    "team": "London Lions",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 2001,
    "number": 1
  },
  {
    "name": "Keenan Evans",
    "team": "London Lions",
    "nationality": "USA",
    "position": "Forward",
    "height": 191,
    "birthYear": 1996,
    "number": 12
  },
  {
    "name": "Landrius Horton",
    "team": "London Lions",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1998,
    "number": 23
  },
  {
    "name": "Maxwell Lewis III",
    "team": "London Lions",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 2002,
    "number": 2
  },
  {
    "name": "Mo Soluade",
    "team": "London Lions",
    "nationality": "United Kingdom",
    "position": "Guard",
    "height": 196,
    "birthYear": 1995,
    "number": 6
  },
  {
    "name": "Tarik Phillip",
    "team": "London Lions",
    "nationality": "United Kingdom",
    "position": "Guard",
    "height": 191,
    "birthYear": 1993,
    "number": 22
  },
  {
    "name": "Thomas Kennedy",
    "team": "London Lions",
    "nationality": "Ireland",
    "position": "Center",
    "height": 207,
    "birthYear": 2000,
    "number": 54
  },
  {
    "name": "Chibuzo Agbo",
    "team": "Manresa",
    "nationality": "USA",
    "position": "Forward",
    "height": 200,
    "birthYear": 2001,
    "number": 11
  },
  {
    "name": "Eric Vila",
    "team": "Manresa",
    "nationality": "Spain",
    "position": "Forward",
    "height": 211,
    "birthYear": 1998,
    "number": 4
  },
  {
    "name": "Ferran Bassas",
    "team": "Manresa",
    "nationality": "Spain",
    "position": "Guard",
    "height": 181,
    "birthYear": 1992,
    "number": 6
  },
  {
    "name": "Hugo Benitez",
    "team": "Manresa",
    "nationality": "France",
    "position": "Guard",
    "height": 192,
    "birthYear": 2001,
    "number": 2
  },
  {
    "name": "JD Notae",
    "team": "Manresa",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 1998,
    "number": 13
  },
  {
    "name": "Lucas Beaufort",
    "team": "Manresa",
    "nationality": "France",
    "position": "Guard",
    "height": 193,
    "birthYear": 2002,
    "number": 5
  },
  {
    "name": "Lukasz Kolenda",
    "team": "Manresa",
    "nationality": "Poland",
    "position": "Guard",
    "height": 196,
    "birthYear": 1999,
    "number": 1
  },
  {
    "name": "Michael Enabulele",
    "team": "Manresa",
    "nationality": "Spain",
    "position": "Center",
    "height": 206,
    "birthYear": 2006,
    "number": 20
  },
  {
    "name": "Nick Ongenda",
    "team": "Manresa",
    "nationality": "Canada",
    "position": "Center",
    "height": 211,
    "birthYear": 2000,
    "number": 14
  },
  {
    "name": "Pablo Tamba",
    "team": "Manresa",
    "nationality": "Spain",
    "position": "Forward",
    "height": 201,
    "birthYear": 2003,
    "number": 8
  },
  {
    "name": "Pierre Oriola",
    "team": "Manresa",
    "nationality": "Spain",
    "position": "Center",
    "height": 208,
    "birthYear": 1992,
    "number": 29
  },
  {
    "name": "Rafa Villar",
    "team": "Manresa",
    "nationality": "Spain",
    "position": "Guard",
    "height": 191,
    "birthYear": 2004,
    "number": 44
  },
  {
    "name": "Timmy Allen",
    "team": "Manresa",
    "nationality": "USA",
    "position": "Forward",
    "height": 198,
    "birthYear": 2000,
    "number": 0
  },
  {
    "name": "Yordan Minchev",
    "team": "Manresa",
    "nationality": "Bulgaria",
    "position": "Forward",
    "height": 203,
    "birthYear": 1998,
    "number": 91
  },
  {
    "name": "Aaron Holiday",
    "team": "Maxima Roma",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 1996,
    "number": 3
  },
  {
    "name": "Brynton Lemar",
    "team": "Maxima Roma",
    "nationality": "USA",
    "position": "Guard",
    "height": 191,
    "birthYear": 1995,
    "number": 11
  },
  {
    "name": "Carl Wheatle",
    "team": "Maxima Roma",
    "nationality": "United Kingdom",
    "position": "Forward",
    "height": 200,
    "birthYear": 1998,
    "number": 10
  },
  {
    "name": "Federico Bonacini",
    "team": "Maxima Roma",
    "nationality": "Italy",
    "position": "Guard",
    "height": 190,
    "birthYear": 1999,
    "number": 23
  },
  {
    "name": "Giovanni Veronesi",
    "team": "Maxima Roma",
    "nationality": "Italy",
    "position": "Forward",
    "height": 197,
    "birthYear": 1998,
    "number": 16
  },
  {
    "name": "Gora Camara",
    "team": "Maxima Roma",
    "nationality": "Senegal",
    "position": "Center",
    "height": 214,
    "birthYear": 2001,
    "number": 29
  },
  {
    "name": "John Brown III",
    "team": "Maxima Roma",
    "nationality": "USA",
    "position": "Center",
    "height": 203,
    "birthYear": 1992,
    "number": 0
  },
  {
    "name": "Matt Ryan",
    "team": "Maxima Roma",
    "nationality": "USA",
    "position": "Forward",
    "height": 198,
    "birthYear": 1997,
    "number": 32
  },
  {
    "name": "Miro Bilan",
    "team": "Maxima Roma",
    "nationality": "Croatia",
    "position": "Center",
    "height": 213,
    "birthYear": 1989,
    "number": 2
  },
  {
    "name": "Mirza Alibegovic",
    "team": "Maxima Roma",
    "nationality": "Italy",
    "position": "Guard",
    "height": 195,
    "birthYear": 1992,
    "number": 5
  },
  {
    "name": "Xavier Moon",
    "team": "Maxima Roma",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 1995,
    "number": 17
  },
  {
    "name": "Andrej Jakimovski",
    "team": "Napoli Basketball",
    "nationality": "North Macedonia",
    "position": "Forward",
    "height": 203,
    "birthYear": 2001,
    "number": 23
  },
  {
    "name": "Guglielmo Caruso",
    "team": "Napoli Basketball",
    "nationality": "Italy",
    "position": "Center",
    "height": 204,
    "birthYear": 1999,
    "number": 30
  },
  {
    "name": "Jack White",
    "team": "Napoli Basketball",
    "nationality": "Australia",
    "position": "Forward",
    "height": 195,
    "birthYear": 1997,
    "number": 14
  },
  {
    "name": "Jahmi'us Ramsey",
    "team": "Napoli Basketball",
    "nationality": "USA",
    "position": "Guard",
    "height": 192,
    "birthYear": 2001,
    "number": 37
  },
  {
    "name": "Jeffrey Dowtin Jr.",
    "team": "Napoli Basketball",
    "nationality": "USA",
    "position": "Guard",
    "height": 191,
    "birthYear": 1997,
    "number": 3
  },
  {
    "name": "John Petrucelli",
    "team": "Napoli Basketball",
    "nationality": "Italy",
    "position": "Guard",
    "height": 193,
    "birthYear": 1992,
    "number": 11
  },
  {
    "name": "Kaleb Tarczewski",
    "team": "Napoli Basketball",
    "nationality": "USA",
    "position": "Center",
    "height": 213,
    "birthYear": 1993,
    "number": 25
  },
  {
    "name": "Leonardo Faggian",
    "team": "Napoli Basketball",
    "nationality": "Italy",
    "position": "Forward",
    "height": 195,
    "birthYear": 2004,
    "number": 10
  },
  {
    "name": "Leonardo Tote",
    "team": "Napoli Basketball",
    "nationality": "Italy",
    "position": "Center",
    "height": 212,
    "birthYear": 1997,
    "number": 35
  },
  {
    "name": "Marco Spissu",
    "team": "Napoli Basketball",
    "nationality": "Italy",
    "position": "Guard",
    "height": 182,
    "birthYear": 1995,
    "number": 0
  },
  {
    "name": "Markel Brown",
    "team": "Napoli Basketball",
    "nationality": "USA",
    "position": "Guard",
    "height": 191,
    "birthYear": 1992,
    "number": 22
  },
  {
    "name": "Zac Seljaas",
    "team": "Napoli Basketball",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1997,
    "number": 1
  },
  {
    "name": "Arnas Berucka",
    "team": "Neptunas",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 196,
    "birthYear": 1997,
    "number": 21
  },
  {
    "name": "Donatas Tarolis",
    "team": "Neptunas",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 202,
    "birthYear": 1994,
    "number": 1
  },
  {
    "name": "Einaras Tubutis",
    "team": "Neptunas",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 204,
    "birthYear": 1998,
    "number": 37
  },
  {
    "name": "Elvar Fridriksson",
    "team": "Neptunas",
    "nationality": "Iceland",
    "position": "Guard",
    "height": 183,
    "birthYear": 1994,
    "number": 10
  },
  {
    "name": "Henri Drell",
    "team": "Neptunas",
    "nationality": "Estonia",
    "position": "Forward",
    "height": 205,
    "birthYear": 2000,
    "number": 0
  },
  {
    "name": "Kristupas Zemaitis",
    "team": "Neptunas",
    "nationality": "Lithuania",
    "position": "Guard",
    "height": 191,
    "birthYear": 1996,
    "number": 13
  },
  {
    "name": "Lukas Kreismontas",
    "team": "Neptunas",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 197,
    "birthYear": 2001,
    "number": 88
  },
  {
    "name": "Martynas Echodas",
    "team": "Neptunas",
    "nationality": "Lithuania",
    "position": "Center",
    "height": 204,
    "birthYear": 1997,
    "number": 14
  },
  {
    "name": "Mindaugas Girdziunas",
    "team": "Neptunas",
    "nationality": "Lithuania",
    "position": "Guard",
    "height": 188,
    "birthYear": 1989,
    "number": 8
  },
  {
    "name": "Raymond Somerville",
    "team": "Neptunas",
    "nationality": "USA",
    "position": "Center",
    "height": 208,
    "birthYear": 2000,
    "number": 17
  },
  {
    "name": "Rytis Sakaitis",
    "team": "Neptunas",
    "nationality": "Lithuania",
    "position": "Guard",
    "height": 193,
    "birthYear": 2004,
    "number": 12
  },
  {
    "name": "Yannick Franke",
    "team": "Neptunas",
    "nationality": "Netherlands",
    "position": "Guard",
    "height": 194,
    "birthYear": 1996,
    "number": 5
  },
  {
    "name": "Alexander Richardson",
    "team": "Niners Chemnitz",
    "nationality": "Germany",
    "position": "Center",
    "height": 206,
    "birthYear": 2003,
    "number": 9
  },
  {
    "name": "Ben Burnham",
    "team": "Niners Chemnitz",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 2002,
    "number": 25
  },
  {
    "name": "Cobe Williams",
    "team": "Niners Chemnitz",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 2000,
    "number": 24
  },
  {
    "name": "Darion Atkins",
    "team": "Niners Chemnitz",
    "nationality": "USA",
    "position": "Center",
    "height": 203,
    "birthYear": 1992,
    "number": 17
  },
  {
    "name": "Elias Roedl",
    "team": "Niners Chemnitz",
    "nationality": "Germany",
    "position": "Forward",
    "height": 198,
    "birthYear": 2002,
    "number": 11
  },
  {
    "name": "Jannis von Seckendorff",
    "team": "Niners Chemnitz",
    "nationality": "Germany",
    "position": "Forward",
    "height": 204,
    "birthYear": 2002,
    "number": 90
  },
  {
    "name": "Luca Kellig",
    "team": "Niners Chemnitz",
    "nationality": "Germany",
    "position": "Guard",
    "height": 192,
    "birthYear": 2006,
    "number": 13
  },
  {
    "name": "Mateo Seric",
    "team": "Niners Chemnitz",
    "nationality": "Germany",
    "position": "Forward",
    "height": 204,
    "birthYear": 1999,
    "number": 21
  },
  {
    "name": "Nighael Ceaser",
    "team": "Niners Chemnitz",
    "nationality": "USA",
    "position": "Center",
    "height": 203,
    "birthYear": 2000,
    "number": 22
  },
  {
    "name": "Phlandrous Fleming Jr.",
    "team": "Niners Chemnitz",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1998,
    "number": 1
  },
  {
    "name": "Stefan Smith",
    "team": "Niners Chemnitz",
    "nationality": "Canada",
    "position": "Guard",
    "height": 188,
    "birthYear": 1999,
    "number": 2
  },
  {
    "name": "Urald King",
    "team": "Niners Chemnitz",
    "nationality": "USA",
    "position": "Forward",
    "height": 198,
    "birthYear": 1990,
    "number": 20
  },
  {
    "name": "Yohan Choupas",
    "team": "Niners Chemnitz",
    "nationality": "France",
    "position": "Guard",
    "height": 193,
    "birthYear": 2000,
    "number": 6
  },
  {
    "name": "Athanasios Bazinas",
    "team": "PAOK",
    "nationality": "Greece",
    "position": "Guard",
    "height": 194,
    "birthYear": 2003,
    "number": 77
  },
  {
    "name": "Ben Moore",
    "team": "PAOK",
    "nationality": "USA",
    "position": "Center",
    "height": 203,
    "birthYear": 1995,
    "number": 26
  },
  {
    "name": "Breein Tyree",
    "team": "PAOK",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 1998,
    "number": 5
  },
  {
    "name": "Cedi Osman",
    "team": "PAOK",
    "nationality": "Turkey",
    "position": "Forward",
    "height": 207,
    "birthYear": 1995,
    "number": 6
  },
  {
    "name": "Clifford Omoruyi",
    "team": "PAOK",
    "nationality": "Nigeria",
    "position": "Center",
    "height": 211,
    "birthYear": 2001,
    "number": 11
  },
  {
    "name": "Dimitrios Kaklamanakis",
    "team": "PAOK",
    "nationality": "Greece",
    "position": "Center",
    "height": 206,
    "birthYear": 1994,
    "number": 14
  },
  {
    "name": "Georgios Fillios",
    "team": "PAOK",
    "nationality": "Greece",
    "position": "Guard",
    "height": 195,
    "birthYear": 2002,
    "number": 25
  },
  {
    "name": "Kyle Alexander",
    "team": "PAOK",
    "nationality": "Canada",
    "position": "Center",
    "height": 208,
    "birthYear": 1996,
    "number": 8
  },
  {
    "name": "Marcus Foster",
    "team": "PAOK",
    "nationality": "USA",
    "position": "Guard",
    "height": 191,
    "birthYear": 1995,
    "number": 17
  },
  {
    "name": "Naz Mitrou-Long",
    "team": "PAOK",
    "nationality": "Canada",
    "position": "Guard",
    "height": 193,
    "birthYear": 1993,
    "number": 1
  },
  {
    "name": "Nick Calathes",
    "team": "PAOK",
    "nationality": "USA",
    "position": "Guard",
    "height": 198,
    "birthYear": 1989,
    "number": 33
  },
  {
    "name": "Nikolaos Persidis",
    "team": "PAOK",
    "nationality": "Greece",
    "position": "Forward",
    "height": 201,
    "birthYear": 1995,
    "number": 18
  },
  {
    "name": "Nikos Chougkaz",
    "team": "PAOK",
    "nationality": "Greece",
    "position": "Forward",
    "height": 204,
    "birthYear": 2000,
    "number": 9
  },
  {
    "name": "Raiquan Gray",
    "team": "PAOK",
    "nationality": "USA",
    "position": "Forward",
    "height": 203,
    "birthYear": 1999,
    "number": 0
  },
  {
    "name": "Trevor Hudgins",
    "team": "PAOK",
    "nationality": "USA",
    "position": "Guard",
    "height": 180,
    "birthYear": 1999,
    "number": 12
  },
  {
    "name": "Armel Traore",
    "team": "Ratiopharm Ulm",
    "nationality": "France",
    "position": "Forward",
    "height": 205,
    "birthYear": 2003,
    "number": 94
  },
  {
    "name": "CJ Anthony Jr.",
    "team": "Ratiopharm Ulm",
    "nationality": "USA",
    "position": "Guard",
    "height": 186,
    "birthYear": 2002,
    "number": 25
  },
  {
    "name": "Devin Schmidt",
    "team": "Ratiopharm Ulm",
    "nationality": "Germany",
    "position": "Guard",
    "height": 190,
    "birthYear": 1994,
    "number": 8
  },
  {
    "name": "Dwayne Koroma",
    "team": "Ratiopharm Ulm",
    "nationality": "Germany",
    "position": "Forward",
    "height": 197,
    "birthYear": 2001,
    "number": 3
  },
  {
    "name": "Ibi Watson",
    "team": "Ratiopharm Ulm",
    "nationality": "USA",
    "position": "Guard",
    "height": 194,
    "birthYear": 1998,
    "number": 2
  },
  {
    "name": "Jaylen Sims",
    "team": "Ratiopharm Ulm",
    "nationality": "USA",
    "position": "Guard",
    "height": 194,
    "birthYear": 1998,
    "number": 30
  },
  {
    "name": "Lenny Liedtke",
    "team": "Ratiopharm Ulm",
    "nationality": "Germany",
    "position": "Forward",
    "height": 198,
    "birthYear": 2004,
    "number": 55
  },
  {
    "name": "Lucas Fischer",
    "team": "Ratiopharm Ulm",
    "nationality": "France",
    "position": "Guard",
    "height": 191,
    "birthYear": 2004,
    "number": 43
  },
  {
    "name": "Marvin Heckel",
    "team": "Ratiopharm Ulm",
    "nationality": "Germany",
    "position": "Guard",
    "height": 190,
    "birthYear": 1997,
    "number": 47
  },
  {
    "name": "Michael Rataj",
    "team": "Ratiopharm Ulm",
    "nationality": "Germany",
    "position": "Forward",
    "height": 200,
    "birthYear": 2003,
    "number": 12
  },
  {
    "name": "Namori Omog",
    "team": "Ratiopharm Ulm",
    "nationality": "Germany",
    "position": "Guard",
    "height": 188,
    "birthYear": 2006,
    "number": 1
  },
  {
    "name": "Simisola Shittu",
    "team": "Ratiopharm Ulm",
    "nationality": "Canada",
    "position": "Center",
    "height": 203,
    "birthYear": 1999,
    "number": 45
  },
  {
    "name": "Amedeo Tessitori",
    "team": "Reyer Venezia",
    "nationality": "Italy",
    "position": "Center",
    "height": 208,
    "birthYear": 1994,
    "number": 0
  },
  {
    "name": "Enoch Boakye",
    "team": "Reyer Venezia",
    "nationality": "Canada",
    "position": "Center",
    "height": 208,
    "birthYear": 2003,
    "number": 13
  },
  {
    "name": "Erick Green",
    "team": "Reyer Venezia",
    "nationality": "USA",
    "position": "Guard",
    "height": 191,
    "birthYear": 1992,
    "number": 32
  },
  {
    "name": "Giga Janelidze",
    "team": "Reyer Venezia",
    "nationality": "Italy",
    "position": "Forward",
    "height": 201,
    "birthYear": 1995,
    "number": 14
  },
  {
    "name": "Giovanni De Nicolao",
    "team": "Reyer Venezia",
    "nationality": "Italy",
    "position": "Guard",
    "height": 187,
    "birthYear": 1996,
    "number": 5
  },
  {
    "name": "Glynn Watson Jr.",
    "team": "Reyer Venezia",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 1997,
    "number": 30
  },
  {
    "name": "Jordan Parks",
    "team": "Reyer Venezia",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1994,
    "number": 22
  },
  {
    "name": "Ky Bowman",
    "team": "Reyer Venezia",
    "nationality": "USA",
    "position": "Guard",
    "height": 190,
    "birthYear": 1997,
    "number": 8
  },
  {
    "name": "Kyle Wiltjer",
    "team": "Reyer Venezia",
    "nationality": "Canada",
    "position": "Forward",
    "height": 208,
    "birthYear": 1992,
    "number": 33
  },
  {
    "name": "Leonardo Candi",
    "team": "Reyer Venezia",
    "nationality": "Italy",
    "position": "Guard",
    "height": 190,
    "birthYear": 1997,
    "number": 7
  },
  {
    "name": "Louis Olinde",
    "team": "Reyer Venezia",
    "nationality": "Germany",
    "position": "Forward",
    "height": 205,
    "birthYear": 1998,
    "number": 19
  },
  {
    "name": "Octavio Maretto",
    "team": "Reyer Venezia",
    "nationality": "Italy",
    "position": "Guard",
    "height": 198,
    "birthYear": 2004,
    "number": 1
  },
  {
    "name": "Sasha Grant",
    "team": "Reyer Venezia",
    "nationality": "Italy",
    "position": "Forward",
    "height": 201,
    "birthYear": 2002,
    "number": 44
  },
  {
    "name": "Sir'Jabari Rice",
    "team": "Reyer Venezia",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1998,
    "number": 10
  },
  {
    "name": "Benjamin Shungu",
    "team": "Riga Zelli",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 1997,
    "number": 2
  },
  {
    "name": "Gustavs Kampuss",
    "team": "Riga Zelli",
    "nationality": "Latvia",
    "position": "Guard",
    "height": 191,
    "birthYear": 1999,
    "number": 6
  },
  {
    "name": "Isaac Johnson",
    "team": "Riga Zelli",
    "nationality": "USA",
    "position": "Center",
    "height": 213,
    "birthYear": 2000,
    "number": 33
  },
  {
    "name": "Ivan Tkachenko",
    "team": "Riga Zelli",
    "nationality": "Ukraine",
    "position": "Forward",
    "height": 197,
    "birthYear": 1997,
    "number": 55
  },
  {
    "name": "Janis Berzins",
    "team": "Riga Zelli",
    "nationality": "Latvia",
    "position": "Forward",
    "height": 201,
    "birthYear": 1993,
    "number": 31
  },
  {
    "name": "Klavs Cavars",
    "team": "Riga Zelli",
    "nationality": "Latvia",
    "position": "Center",
    "height": 206,
    "birthYear": 1996,
    "number": 15
  },
  {
    "name": "Kristians Feierbergs",
    "team": "Riga Zelli",
    "nationality": "Latvia",
    "position": "Forward",
    "height": 202,
    "birthYear": 2002,
    "number": 11
  },
  {
    "name": "Martynas Varnas",
    "team": "Riga Zelli",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 196,
    "birthYear": 1997,
    "number": 13
  },
  {
    "name": "Rolands Sulcs",
    "team": "Riga Zelli",
    "nationality": "Latvia",
    "position": "Guard",
    "height": 190,
    "birthYear": 2006,
    "number": 10
  },
  {
    "name": "Toms Skuja",
    "team": "Riga Zelli",
    "nationality": "Latvia",
    "position": "Guard",
    "height": 191,
    "birthYear": 2002,
    "number": 3
  },
  {
    "name": "Tony Perkins",
    "team": "Riga Zelli",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 2001,
    "number": 1
  },
  {
    "name": "Tyler Wahl",
    "team": "Riga Zelli",
    "nationality": "USA",
    "position": "Forward",
    "height": 206,
    "birthYear": 2001,
    "number": 5
  },
  {
    "name": "Andrea Mezzanotte",
    "team": "Roma Basketball",
    "nationality": "Italy",
    "position": "Forward",
    "height": 208,
    "birthYear": 1998,
    "number": 24
  },
  {
    "name": "Arturs Strautins",
    "team": "Roma Basketball",
    "nationality": "Latvia",
    "position": "Forward",
    "height": 198,
    "birthYear": 1998,
    "number": 12
  },
  {
    "name": "Corey Davis Jr.",
    "team": "Roma Basketball",
    "nationality": "USA",
    "position": "Guard",
    "height": 185,
    "birthYear": 1997,
    "number": 5
  },
  {
    "name": "Erik Stevenson",
    "team": "Roma Basketball",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1999,
    "number": 10
  },
  {
    "name": "Gerald Ayayi",
    "team": "Roma Basketball",
    "nationality": "France",
    "position": "Guard",
    "height": 188,
    "birthYear": 2001,
    "number": 11
  },
  {
    "name": "Giovanni Emejuru",
    "team": "Roma Basketball",
    "nationality": "Italy",
    "position": "Center",
    "height": 210,
    "birthYear": 2002,
    "number": 7
  },
  {
    "name": "Marko Simonovic",
    "team": "Roma Basketball",
    "nationality": "Montenegro",
    "position": "Center",
    "height": 213,
    "birthYear": 1999,
    "number": 19
  },
  {
    "name": "Michael Iuzzolino",
    "team": "Roma Basketball",
    "nationality": "USA",
    "position": "Guard",
    "height": 191,
    "birthYear": 2001,
    "number": 33
  },
  {
    "name": "Nico Mannion",
    "team": "Roma Basketball",
    "nationality": "Italy",
    "position": "Guard",
    "height": 188,
    "birthYear": 2001,
    "number": 1
  },
  {
    "name": "Paul Watson Jr.",
    "team": "Roma Basketball",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1994,
    "number": 3
  },
  {
    "name": "Trentyn Flowers",
    "team": "Roma Basketball",
    "nationality": "USA",
    "position": "Forward",
    "height": 206,
    "birthYear": 2005,
    "number": 9
  },
  {
    "name": "Artur Konontsuk",
    "team": "Rostock Seawolves",
    "nationality": "Estonia",
    "position": "Forward",
    "height": 202,
    "birthYear": 2000,
    "number": 34
  },
  {
    "name": "Bent Leuchten",
    "team": "Rostock Seawolves",
    "nationality": "Germany",
    "position": "Center",
    "height": 214,
    "birthYear": 2002,
    "number": 51
  },
  {
    "name": "DeAndre Lansdowne",
    "team": "Rostock Seawolves",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 1989,
    "number": 9
  },
  {
    "name": "Dominic Lockhart",
    "team": "Rostock Seawolves",
    "nationality": "Germany",
    "position": "Forward",
    "height": 199,
    "birthYear": 1994,
    "number": 3
  },
  {
    "name": "Elias Baggette",
    "team": "Rostock Seawolves",
    "nationality": "Germany",
    "position": "Guard",
    "height": 181,
    "birthYear": 2002,
    "number": 4
  },
  {
    "name": "Isayah Owens",
    "team": "Rostock Seawolves",
    "nationality": "USA",
    "position": "Guard",
    "height": 187,
    "birthYear": 2002,
    "number": 6
  },
  {
    "name": "Johnathan Stove",
    "team": "Rostock Seawolves",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1995,
    "number": 22
  },
  {
    "name": "Matthes Tilsen",
    "team": "Rostock Seawolves",
    "nationality": "Germany",
    "position": "Forward",
    "height": 196,
    "birthYear": 2006,
    "number": 31
  },
  {
    "name": "Owen Klassen",
    "team": "Rostock Seawolves",
    "nationality": "Canada",
    "position": "Center",
    "height": 208,
    "birthYear": 1991,
    "number": 29
  },
  {
    "name": "Philipp Hartwich",
    "team": "Rostock Seawolves",
    "nationality": "Germany",
    "position": "Center",
    "height": 218,
    "birthYear": 1995,
    "number": 7
  },
  {
    "name": "Robin Amaize",
    "team": "Rostock Seawolves",
    "nationality": "Germany",
    "position": "Forward",
    "height": 196,
    "birthYear": 1994,
    "number": 15
  },
  {
    "name": "TJ Crockett Jr.",
    "team": "Rostock Seawolves",
    "nationality": "USA",
    "position": "Guard",
    "height": 187,
    "birthYear": 1999,
    "number": 0
  },
  {
    "name": "Todd Withers",
    "team": "Rostock Seawolves",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1996,
    "number": 33
  },
  {
    "name": "Zach Copeland",
    "team": "Rostock Seawolves",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 1997,
    "number": 2
  },
  {
    "name": "Balsa Koprivica",
    "team": "San Pablo Burgos",
    "nationality": "Serbia",
    "position": "Center",
    "height": 216,
    "birthYear": 2000,
    "number": 7
  },
  {
    "name": "Chase Audige",
    "team": "San Pablo Burgos",
    "nationality": "Jamaica",
    "position": "Guard",
    "height": 193,
    "birthYear": 1999,
    "number": 1
  },
  {
    "name": "Christian Sengfelder",
    "team": "San Pablo Burgos",
    "nationality": "Germany",
    "position": "Forward",
    "height": 203,
    "birthYear": 1995,
    "number": 43
  },
  {
    "name": "Daniel Diez",
    "team": "San Pablo Burgos",
    "nationality": "Spain",
    "position": "Forward",
    "height": 201,
    "birthYear": 1993,
    "number": 11
  },
  {
    "name": "DJ Steward",
    "team": "San Pablo Burgos",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 2001,
    "number": 4
  },
  {
    "name": "Dusan Radosavljevic",
    "team": "San Pablo Burgos",
    "nationality": "Serbia",
    "position": "Forward",
    "height": 201,
    "birthYear": 2001,
    "number": 15
  },
  {
    "name": "Pablo Almazan",
    "team": "San Pablo Burgos",
    "nationality": "Spain",
    "position": "Forward",
    "height": 200,
    "birthYear": 1989,
    "number": 8
  },
  {
    "name": "Raul Lobaco",
    "team": "San Pablo Burgos",
    "nationality": "Spain",
    "position": "Guard",
    "height": 190,
    "birthYear": 2000,
    "number": 55
  },
  {
    "name": "Retin Obasohan",
    "team": "San Pablo Burgos",
    "nationality": "Belgium",
    "position": "Guard",
    "height": 185,
    "birthYear": 1993,
    "number": 32
  },
  {
    "name": "Ruben Guerrero",
    "team": "San Pablo Burgos",
    "nationality": "Spain",
    "position": "Center",
    "height": 213,
    "birthYear": 1995,
    "number": 12
  },
  {
    "name": "Sekou Doumbouya",
    "team": "San Pablo Burgos",
    "nationality": "France",
    "position": "Center",
    "height": 205,
    "birthYear": 2000,
    "number": 45
  },
  {
    "name": "Ziga Samar",
    "team": "San Pablo Burgos",
    "nationality": "Slovenia",
    "position": "Guard",
    "height": 197,
    "birthYear": 2001,
    "number": 5
  },
  {
    "name": "Cedric Henderson Jr.",
    "team": "Siauliai",
    "nationality": "USA",
    "position": "Guard",
    "height": 198,
    "birthYear": 2000,
    "number": 2
  },
  {
    "name": "Dayvion McKnight",
    "team": "Siauliai",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 2002,
    "number": 20
  },
  {
    "name": "Dovydas Romancenko",
    "team": "Siauliai",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 206,
    "birthYear": 1998,
    "number": 25
  },
  {
    "name": "Efton Reid",
    "team": "Siauliai",
    "nationality": "USA",
    "position": "Center",
    "height": 213,
    "birthYear": 2002,
    "number": 15
  },
  {
    "name": "Erikas Venskus",
    "team": "Siauliai",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 205,
    "birthYear": 2000,
    "number": 21
  },
  {
    "name": "Karolis Lukosiunas",
    "team": "Siauliai",
    "nationality": "Lithuania",
    "position": "Guard",
    "height": 195,
    "birthYear": 1997,
    "number": 16
  },
  {
    "name": "Martynas Pacevicius",
    "team": "Siauliai",
    "nationality": "Lithuania",
    "position": "Center",
    "height": 205,
    "birthYear": 1997,
    "number": 9
  },
  {
    "name": "Michael Caffey",
    "team": "Siauliai",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 1993,
    "number": 55
  },
  {
    "name": "Rokas Civilis",
    "team": "Siauliai",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 195,
    "birthYear": 2005,
    "number": 77
  },
  {
    "name": "Selim Fofana",
    "team": "Siauliai",
    "nationality": "Switzerland",
    "position": "Guard",
    "height": 193,
    "birthYear": 1999,
    "number": 7
  },
  {
    "name": "Simas Jarumbauskas",
    "team": "Siauliai",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 197,
    "birthYear": 2000,
    "number": 17
  },
  {
    "name": "Tauras Jogela",
    "team": "Siauliai",
    "nationality": "Lithuania",
    "position": "Forward",
    "height": 203,
    "birthYear": 1993,
    "number": 22
  },
  {
    "name": "Dusan Nikolic",
    "team": "Skyliners Frankfurt",
    "nationality": "Germany",
    "position": "Guard",
    "height": 196,
    "birthYear": 2005,
    "number": 14
  },
  {
    "name": "Isaiah Swope",
    "team": "Skyliners Frankfurt",
    "nationality": "USA",
    "position": "Guard",
    "height": 178,
    "birthYear": 2003,
    "number": 1
  },
  {
    "name": "Jacob Knauf",
    "team": "Skyliners Frankfurt",
    "nationality": "Germany",
    "position": "Center",
    "height": 210,
    "birthYear": 1997,
    "number": 25
  },
  {
    "name": "Judah Mintz",
    "team": "Skyliners Frankfurt",
    "nationality": "USA",
    "position": "Guard",
    "height": 190,
    "birthYear": 2003,
    "number": 10
  },
  {
    "name": "Moses Poelking",
    "team": "Skyliners Frankfurt",
    "nationality": "Germany",
    "position": "Center",
    "height": 206,
    "birthYear": 1997,
    "number": 6
  },
  {
    "name": "Nahiem Alleyne",
    "team": "Skyliners Frankfurt",
    "nationality": "USA",
    "position": "Guard",
    "height": 193,
    "birthYear": 2001,
    "number": 4
  },
  {
    "name": "Race Thompson",
    "team": "Skyliners Frankfurt",
    "nationality": "USA",
    "position": "Center",
    "height": 203,
    "birthYear": 1999,
    "number": 5
  },
  {
    "name": "Radii Caisin",
    "team": "Skyliners Frankfurt",
    "nationality": "Germany",
    "position": "Forward",
    "height": 198,
    "birthYear": 2001,
    "number": 15
  },
  {
    "name": "Roman Bedime",
    "team": "Skyliners Frankfurt",
    "nationality": "Germany",
    "position": "Center",
    "height": 203,
    "birthYear": 2001,
    "number": 35
  },
  {
    "name": "Ryan Arcidiacono",
    "team": "Skyliners Frankfurt",
    "nationality": "USA",
    "position": "Guard",
    "height": 190,
    "birthYear": 1994,
    "number": 51
  },
  {
    "name": "Thomas Klepeisz",
    "team": "Skyliners Frankfurt",
    "nationality": "Austria",
    "position": "Guard",
    "height": 186,
    "birthYear": 1991,
    "number": 22
  },
  {
    "name": "Till Pape",
    "team": "Skyliners Frankfurt",
    "nationality": "Germany",
    "position": "Forward",
    "height": 206,
    "birthYear": 1997,
    "number": 19
  },
  {
    "name": "William Christmas",
    "team": "Skyliners Frankfurt",
    "nationality": "USA",
    "position": "Guard",
    "height": 196,
    "birthYear": 1996,
    "number": 8
  },
  {
    "name": "Anthony Hickey",
    "team": "Slask Wroclaw",
    "nationality": "USA",
    "position": "Guard",
    "height": 180,
    "birthYear": 1992,
    "number": 2
  },
  {
    "name": "Anthony Wrzeszcz",
    "team": "Slask Wroclaw",
    "nationality": "Poland",
    "position": "Guard",
    "height": 193,
    "birthYear": 2004,
    "number": 8
  },
  {
    "name": "Blazej Czerniewicz",
    "team": "Slask Wroclaw",
    "nationality": "Poland",
    "position": "Guard",
    "height": 198,
    "birthYear": 2002,
    "number": 27
  },
  {
    "name": "Blazej Kulikowski",
    "team": "Slask Wroclaw",
    "nationality": "Poland",
    "position": "Guard",
    "height": 193,
    "birthYear": 2001,
    "number": 11
  },
  {
    "name": "Devin Robinson",
    "team": "Slask Wroclaw",
    "nationality": "USA",
    "position": "Forward",
    "height": 203,
    "birthYear": 1995,
    "number": 5
  },
  {
    "name": "Isaih Moore",
    "team": "Slask Wroclaw",
    "nationality": "USA",
    "position": "Center",
    "height": 208,
    "birthYear": 2000,
    "number": 13
  },
  {
    "name": "Jakub Niziol",
    "team": "Slask Wroclaw",
    "nationality": "Poland",
    "position": "Forward",
    "height": 201,
    "birthYear": 1996,
    "number": 35
  },
  {
    "name": "John Egbunu",
    "team": "Slask Wroclaw",
    "nationality": "Nigeria",
    "position": "Center",
    "height": 208,
    "birthYear": 1994,
    "number": 15
  },
  {
    "name": "Kyrell Luc",
    "team": "Slask Wroclaw",
    "nationality": "USA",
    "position": "Guard",
    "height": 180,
    "birthYear": 2002,
    "number": 4
  },
  {
    "name": "Malik Parsons",
    "team": "Slask Wroclaw",
    "nationality": "USA",
    "position": "Guard",
    "height": 190,
    "birthYear": 1999,
    "number": 3
  },
  {
    "name": "Tymoteusz Sternicki",
    "team": "Slask Wroclaw",
    "nationality": "Poland",
    "position": "Forward",
    "height": 204,
    "birthYear": 2006,
    "number": 22
  },
  {
    "name": "Bryce Jones",
    "team": "Tofas",
    "nationality": "USA",
    "position": "Guard",
    "height": 183,
    "birthYear": 1994,
    "number": 32
  },
  {
    "name": "Efe Postel",
    "team": "Tofas",
    "nationality": "Turkey",
    "position": "Guard",
    "height": 190,
    "birthYear": 2006,
    "number": 22
  },
  {
    "name": "Gabriel Brown",
    "team": "Tofas",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 2000,
    "number": 44
  },
  {
    "name": "Jamuni McNeace",
    "team": "Tofas",
    "nationality": "USA",
    "position": "Center",
    "height": 208,
    "birthYear": 1996,
    "number": 8
  },
  {
    "name": "Leon Apaydin",
    "team": "Tofas",
    "nationality": "Turkey",
    "position": "Forward",
    "height": 198,
    "birthYear": 1999,
    "number": 55
  },
  {
    "name": "Sadik Kabaca",
    "team": "Tofas",
    "nationality": "Turkey",
    "position": "Forward",
    "height": 208,
    "birthYear": 2000,
    "number": 6
  },
  {
    "name": "Shavar Reynolds Jr.",
    "team": "Tofas",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 1998,
    "number": 33
  },
  {
    "name": "Terrell Carter II",
    "team": "Tofas",
    "nationality": "USA",
    "position": "Center",
    "height": 208,
    "birthYear": 1996,
    "number": 5
  },
  {
    "name": "Tre'Shawn Thurman",
    "team": "Tofas",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 1995,
    "number": 15
  },
  {
    "name": "Yigitcan Saybir",
    "team": "Tofas",
    "nationality": "Turkey",
    "position": "Forward",
    "height": 204,
    "birthYear": 1999,
    "number": 3
  },
  {
    "name": "Zach Nutall",
    "team": "Tofas",
    "nationality": "USA",
    "position": "Guard",
    "height": 190,
    "birthYear": 1999,
    "number": 10
  },
  {
    "name": "Alessandro Bertini",
    "team": "Trento",
    "nationality": "Italy",
    "position": "Forward",
    "height": 195,
    "birthYear": 2002,
    "number": 5
  },
  {
    "name": "Charlie Brown Jr.",
    "team": "Trento",
    "nationality": "USA",
    "position": "Forward",
    "height": 198,
    "birthYear": 1997,
    "number": 4
  },
  {
    "name": "Darius Brown II",
    "team": "Trento",
    "nationality": "USA",
    "position": "Guard",
    "height": 188,
    "birthYear": 1999,
    "number": 0
  },
  {
    "name": "Isaiah Bigelow",
    "team": "Trento",
    "nationality": "USA",
    "position": "Forward",
    "height": 201,
    "birthYear": 2000,
    "number": 24
  },
  {
    "name": "Jordan Bayehe",
    "team": "Trento",
    "nationality": "Cameroon",
    "position": "Center",
    "height": 206,
    "birthYear": 1999,
    "number": 26
  },
  {
    "name": "Quincy Olivari",
    "team": "Trento",
    "nationality": "USA",
    "position": "Guard",
    "height": 191,
    "birthYear": 2001,
    "number": 8
  },
  {
    "name": "Selom Mawugbe",
    "team": "Trento",
    "nationality": "USA",
    "position": "Center",
    "height": 208,
    "birthYear": 1998,
    "number": 21
  },
  {
    "name": "Toto Forray",
    "team": "Trento",
    "nationality": "Argentina",
    "position": "Guard",
    "height": 187,
    "birthYear": 1986,
    "number": 10
  },
  {
    "name": "Anthony Lamb",
    "team": "Turk Telekom",
    "nationality": "USA",
    "position": "Forward",
    "height": 198,
    "birthYear": 1998,
    "number": 22
  },
  {
    "name": "Ata Kahraman",
    "team": "Turk Telekom",
    "nationality": "Turkey",
    "position": "Guard",
    "height": 195,
    "birthYear": 1999,
    "number": 6
  },
  {
    "name": "Dogus Ozdemiroglu",
    "team": "Turk Telekom",
    "nationality": "Turkey",
    "position": "Guard",
    "height": 194,
    "birthYear": 1996,
    "number": 18
  },
  {
    "name": "Emircan Kosut",
    "team": "Turk Telekom",
    "nationality": "Turkey",
    "position": "Center",
    "height": 216,
    "birthYear": 1995,
    "number": 9
  },
  {
    "name": "Goktug Bas",
    "team": "Turk Telekom",
    "nationality": "Turkey",
    "position": "Forward",
    "height": 201,
    "birthYear": 2001,
    "number": 57
  },
  {
    "name": "Ismael Bako",
    "team": "Turk Telekom",
    "nationality": "Belgium",
    "position": "Center",
    "height": 208,
    "birthYear": 1995,
    "number": 28
  },
  {
    "name": "Jerrick Harding",
    "team": "Turk Telekom",
    "nationality": "USA",
    "position": "Guard",
    "height": 185,
    "birthYear": 1998,
    "number": 7
  },
  {
    "name": "Kris Bankston",
    "team": "Turk Telekom",
    "nationality": "USA",
    "position": "Center",
    "height": 205,
    "birthYear": 1999,
    "number": 30
  },
  {
    "name": "Mete Tekcevik",
    "team": "Turk Telekom",
    "nationality": "Turkey",
    "position": "Guard",
    "height": 185,
    "birthYear": 2001,
    "number": 55
  },
  {
    "name": "Shaquielle McKissic",
    "team": "Turk Telekom",
    "nationality": "USA",
    "position": "Forward",
    "height": 196,
    "birthYear": 1990,
    "number": 77
  },
  {
    "name": "Tim Schneider",
    "team": "Turk Telekom",
    "nationality": "Germany",
    "position": "Forward",
    "height": 208,
    "birthYear": 1997,
    "number": 3
  },
  {
    "name": "Tony Taylor",
    "team": "Turk Telekom",
    "nationality": "USA",
    "position": "Guard",
    "height": 185,
    "birthYear": 1990,
    "number": 21
  },
  {
    "name": "Uros Trifunovic",
    "team": "Turk Telekom",
    "nationality": "Serbia",
    "position": "Forward",
    "height": 200,
    "birthYear": 2000,
    "number": 10
  }
];
