/* Path Between — six degrees of EuroLeague: link Player A to Player B through
 * shared teammates. Every guess must have played WITH the previous player —
 * same club, same season, judged by the careers we store. Right or wrong,
 * every guess costs one; you get par + 3. Each player can be used once.
 * Modes: Daily (par-3 pair, date-seeded, streak) + Easy/Medium/Hard practice
 * (one / two / three players in between). Puzzles = window.PATHS (paths.js,
 * generated by build_paths.js — which loads THIS file for its teammate graph,
 * so generator and game can never disagree about who played with whom).
 * Self-contained IIFE; exposes window.PathBetween. */
(function () {
  "use strict";

  var CAREERS = window.CAREERS || [];
  var SLACK = 3;                     // guesses = par + SLACK

  var K = {
    mode: "elg:pb:mode", stats: "elg:pb:stats", dstats: "elg:pb:dstats",
    seen: "elg:pb:seenhelp",
    daily: function (d) { return "elg:pb:daily:" + d; }
  };
  function lsGet(k, f) { try { var v = window.localStorage.getItem(k); return v == null ? f : JSON.parse(v); } catch (e) { return f; } }
  function lsSet(k, v) { try { window.localStorage.setItem(k, JSON.stringify(v)); } catch (e) {} }
  function norm(s) { return String(s).toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, ""); }

  function pad(n) { return n < 10 ? "0" + n : "" + n; }
  function dateStr(d) { return d.getFullYear() + "-" + pad(d.getMonth() + 1) + "-" + pad(d.getDate()); }
  function todayStr() { return dateStr(new Date()); }
  function yesterdayStr() { var d = new Date(); d.setDate(d.getDate() - 1); return dateStr(d); }
  function hashStr(s) { var h = 2166136261 >>> 0; for (var i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }

  function initials(name) { var p = String(name).trim().split(/\s+/); return ((p[0] || "")[0] || "") + ((p[1] || "")[0] || ""); }
  function avatarColor(name) { var h = 0; for (var i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) >>> 0; return "hsl(" + (h % 360) + ",45%,42%)"; }

  // --- Club aliases: the same club stored under different names --------------
  // careers.js keeps the name each source used ("Elan Chalon" vs "Chalon"),
  // which would silently drop teammate edges. Merge KNOWN same-club variants
  // only — lookalikes like Virtus/Fortitudo Bologna or FC Barcelona B are
  // genuinely different teams and stay apart.
  var ALIAS = {
    "Antibes Sharks": "Antibes",
    "Elan Chalon": "Chalon",
    "CB Estudiantes": "Estudiantes",            // Madrid (Bahia Blanca stays separate)
    "Joventut Badalona": "Joventut",
    "JSF Nanterre": "Nanterre",
    "Nanterre 92": "Nanterre",
    "Paris-Levallois": "Metropolitans 92",       // one franchise, three era names
    "Levallois Metropolitans": "Metropolitans 92",
    "Buducnost Podgorica": "Buducnost",
    "Baxi Manresa": "Manresa",
    "Aquila Basket Trento": "Trento",
    "Benetton Treviso": "Treviso",
    "Pallacanestro Varese": "Varese",
    "Union Olimpija": "Olimpija Ljubljana",
    "Wollongong Hawks": "Illawarra Hawks"
  };
  function club(team) { return ALIAS[team] || team; }

  var INF = 9999;
  function yrs(from, to) { return to == null ? from + "–" : from + "–" + String(to).slice(2); }

  // --- Teammate graph over careers.js -----------------------------------------
  var UNIVERSE = null;               // name → { name, stints: [{club, from, to}] }
  function universe() {
    if (UNIVERSE) return UNIVERSE;
    var u = {};
    CAREERS.forEach(function (c) {
      u[c.name] = {
        name: c.name,
        stints: c.career.map(function (s) { return { club: club(s.team), from: s.from, to: s.to == null ? INF : s.to }; })
      };
    });
    UNIVERSE = u;
    return u;
  }
  // Shared club + overlapping years → they were teammates. Returns the nicest
  // (longest, then earliest) shared window for display, or null.
  function link(a, b) {
    var ua = universe()[a], ub = universe()[b];
    if (!ua || !ub || a === b) return null;
    var best = null;
    ua.stints.forEach(function (sa) {
      ub.stints.forEach(function (sb) {
        if (sa.club !== sb.club) return;
        var s = Math.max(sa.from, sb.from), e = Math.min(sa.to, sb.to);
        if (s >= e) return;
        if (!best || (e - s) > (best.e - best.s) || ((e - s) === (best.e - best.s) && s < best.s)) best = { club: sa.club, s: s, e: e };
      });
    });
    return best;
  }
  function linkLabel(l) { return l.club + " " + yrs(l.s, l.e === INF ? null : l.e); }
  var ADJ = null;                    // name → [teammate names] (careers.js order)
  function adjacency() {
    if (ADJ) return ADJ;
    var u = universe(), names = CAREERS.map(function (c) { return c.name; });
    ADJ = {};
    names.forEach(function (n) { ADJ[n] = []; });
    for (var i = 0; i < names.length; i++) {
      for (var j = i + 1; j < names.length; j++) {
        if (link(names[i], names[j])) { ADJ[names[i]].push(names[j]); ADJ[names[j]].push(names[i]); }
      }
    }
    return ADJ;
  }
  function teammates(name) { return adjacency()[name] || []; }
  function bfs(src) {                // distances + a parent tree (deterministic)
    var adj = adjacency(), dist = {}, prev = {};
    dist[src] = 0;
    var q = [src];
    for (var h = 0; h < q.length; h++) {
      var v = q[h];
      teammates(v).forEach(function (w) {
        if (dist[w] == null) { dist[w] = dist[v] + 1; prev[w] = v; q.push(w); }
      });
    }
    return { dist: dist, prev: prev };
  }
  function route(a, b) {             // one shortest chain a→…→b (list of names)
    var r = bfs(a);
    if (r.dist[b] == null) return null;
    var out = [b];
    while (out[0] !== a) out.unshift(r.prev[out[0]]);
    return out;
  }

  var els = {};
  function $(id) { return document.getElementById(id); }

  var PATHS = window.PATHS || [];
  var BAND = { easy: 2, medium: 3, hard: 4 };
  var POOLS = null;                  // par → [puzzle index] (daily draws from par 3)
  function pools() {
    if (POOLS) return POOLS;
    POOLS = { 2: [], 3: [], 4: [] };
    PATHS.forEach(function (p, i) { if (POOLS[p.par]) POOLS[p.par].push(i); });
    return POOLS;
  }

  var mode = "daily";                // "daily" | "easy" | "medium" | "hard"
  var dayKey = todayStr();           // the date the Daily engine is playing (Archive replays a past one)
  var isArchive = false, pendingArchive = null;
  var pIdx = -1, start = null, target = null, par = 0;
  var chain = [], left = 0, wrong = 0, misses = [];   // misses = tried-and-failed for the CURRENT chain end
  var over = false, won = false, dealt = false;
  var matches = [], activeIndex = -1;

  function modeLabel() { return mode === "daily" ? (isArchive ? "Archive " + dayKey : "Daily") : mode.charAt(0).toUpperCase() + mode.slice(1); }
  function dailyIdx() { var m = pools()[3]; return m.length ? m[hashStr("pb:" + dayKey) % m.length] : -1; }
  function end() { return chain[chain.length - 1]; }
  function steps() { return chain.length - 1; }        // links built so far

  // --- Stats: practice (simple) + daily (streak) ------------------------------
  function defaultStats() { return { played: 0, solved: 0, curStreak: 0, maxStreak: 0 }; }
  function getStats() { return lsGet(K.stats, null) || defaultStats(); }
  function record(winFlag) {
    var s = getStats(); s.played++;
    if (winFlag) { s.solved++; s.curStreak++; if (s.curStreak > s.maxStreak) s.maxStreak = s.curStreak; } else s.curStreak = 0;
    lsSet(K.stats, s); return s;
  }
  function defaultDStats() { return { played: 0, solved: 0, curStreak: 0, maxStreak: 0, lastDate: null, lastWon: false }; }
  function getDStats() { return lsGet(K.dstats, null) || defaultDStats(); }
  function recordDaily(winFlag) {
    var s = getDStats();
    if (isArchive) return s;                   // archive replays never touch streaks
    if (s.lastDate === todayStr()) return s;
    s.played++;
    if (winFlag) { s.solved++; s.curStreak = (s.lastDate === yesterdayStr() && s.lastWon) ? s.curStreak + 1 : 1; if (s.curStreak > s.maxStreak) s.maxStreak = s.curStreak; }
    else s.curStreak = 0;
    s.lastDate = todayStr(); s.lastWon = winFlag;
    lsSet(K.dstats, s); return s;
  }
  function renderStats() {
    if (!els.stats) return;
    if (mode === "daily") {
      var s = getDStats();
      var live = (s.lastDate === todayStr() || s.lastDate === yesterdayStr()) ? s.curStreak : 0;
      els.stats.textContent = "Daily · Solved " + s.solved + "/" + s.played + " · Streak " + live + " · Best " + s.maxStreak;
    } else {
      var p = getStats();
      els.stats.textContent = "Solved " + p.solved + "/" + p.played + " · Streak " + p.curStreak + " · Best " + p.maxStreak;
    }
  }

  // --- Rendering ---------------------------------------------------------------
  function careerLine(name) {        // the player's whole path — the map you route with
    var u = universe()[name];
    if (!u) return "";
    return u.stints.map(function (s) { return s.club + " " + yrs(s.from, s.to === INF ? null : s.to); }).join(" · ");
  }
  function chainRow(rank, name, meta, dossier) {
    var row = document.createElement("div"); row.className = "pb-row";
    var head = document.createElement("div"); head.className = "pb-row-head";
    var rk = document.createElement("span"); rk.className = "pb-rank"; rk.textContent = rank;
    var nm = document.createElement("span"); nm.className = "pb-name"; nm.textContent = name;
    var mt = document.createElement("span"); mt.className = "pb-meta"; mt.textContent = meta;
    head.appendChild(rk); head.appendChild(nm); head.appendChild(mt);
    row.appendChild(head);
    if (dossier) {
      var d = document.createElement("div"); d.className = "pb-career"; d.textContent = careerLine(name);
      row.appendChild(d);
    }
    return row;
  }
  function renderChain() {
    els.chain.innerHTML = "";
    for (var i = 0; i < chain.length; i++) {
      var meta = i === 0 ? "start" : "via " + linkLabel(link(chain[i - 1], chain[i]));
      var isEnd = i === chain.length - 1;
      els.chain.appendChild(chainRow(String(i + 1), chain[i], meta, isEnd && !over && !won));
    }
    if (!won) {
      var gap = document.createElement("div"); gap.className = "pb-gap";
      gap.textContent = over ? "· · ·" : "· · ·";
      els.chain.appendChild(gap);
      els.chain.appendChild(chainRow("", target, "target", !over));
    }
    if (els.input) els.input.placeholder = over ? "" : "Name a teammate of " + end() + "…";
  }
  function renderMisses() {
    els.guesses.innerHTML = "";
    misses.forEach(function (g) {
      var d = document.createElement("div"); d.className = "pid-wrong";
      d.textContent = "✗ " + g + " — never with " + end() + " (in our data)";
      els.guesses.appendChild(d);
    });
  }
  function updateCounter() {
    if (over) { els.counter.textContent = modeLabel() + " · " + (won ? "Connected in " + steps() + (steps() === par ? " — right on par! 🎉" : " (par " + par + ")") : "Not connected"); return; }
    els.counter.textContent = modeLabel() + " · Par " + par + " · " + left + (left === 1 ? " guess left — make it count!" : " guesses left");
  }
  function updateButtons() {
    if (els.next) els.next.style.display = (mode === "daily") ? "none" : "";
    if (els.giveup) els.giveup.style.display = (mode === "daily") ? "none" : "";
  }
  function flash(msg) { if (els.flash) { els.flash.textContent = msg; els.flash.hidden = !msg; } }

  function routeText(names) {        // "A → B (Club 12–14) → C (Club 19–)"
    return names.map(function (n, i) {
      return i === 0 ? n : n + " (" + linkLabel(link(names[i - 1], n)) + ")";
    }).join(" → ");
  }
  function dailyBannerNote() {
    if (mode !== "daily") return "";
    if (isArchive) return "<br>That was the " + dayKey + " edition.";
    if (!won) return "<br>A new pair lands at midnight — come back for revenge!";
    var s = getDStats();
    return s.curStreak >= 2 ? "<br>🔥 <strong>" + s.curStreak + "-day streak</strong> — see you tomorrow!"
                            : "<br>Come back tomorrow for a new pair. 👋";
  }
  function escapeHtml(s) { return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
  function shareText() {
    var row = "", i;
    for (i = 0; i < steps(); i++) row += "🟩";
    if (!won) row += "⬛";
    var score = "Par " + par + " · " + (won ? "connected in " + steps() : "not connected") +
      (wrong ? " · " + wrong + (wrong === 1 ? " miss" : " misses") : "");
    return "Path Between 🏀 " + dayKey + "\n" + score + "\n" + row +
      (window.ELG ? "\n" + window.ELG.shareURL("pathbetween") : "");
  }
  function addShareBtn(actions) {
    if (!actions) return;
    var b = document.createElement("button"); b.type = "button"; b.className = "share-btn alt";
    b.textContent = "Share result";
    b.addEventListener("click", function () { if (window.ELG) window.ELG.copyShare(shareText(), b); });
    actions.appendChild(b);
  }
  function showBanner(deadEnd) {
    els.banner.className = "banner " + (won ? "win" : "lose");
    els.banner.innerHTML = "";
    var title = document.createElement("div"); title.className = "banner-title";
    title.textContent = won
      ? (steps() === par && wrong === 0 ? "🤩 Perfect route!" : steps() === par ? "🎯 Right on par!" : "🏆 Connected!")
      : (deadEnd ? "😔 Dead end…" : "😔 The trail went cold…");
    var sub = document.createElement("div"); sub.className = "banner-sub";
    var html;
    if (won) {
      html = "<span class='pname'>" + escapeHtml(start) + "</span> → <span class='pname'>" + escapeHtml(target) + "</span> in <strong>" +
        steps() + (steps() === 1 ? " step" : " steps") + "</strong>" +
        (steps() === par ? " — the shortest possible" : " (shortest was " + par + ")") +
        (wrong ? ", " + wrong + (wrong === 1 ? " miss" : " misses") + " along the way." : ", not a single miss.");
    } else {
      var r = route(start, target);
      html = (deadEnd ? "No unused teammate of <strong>" + escapeHtml(end()) + "</strong> left to play. " : "") +
        "One route: " + escapeHtml(r ? routeText(r) : "—") + ".";
    }
    sub.innerHTML = html + dailyBannerNote();
    var actions = document.createElement("div"); actions.className = "banner-actions";
    var btn = document.createElement("button"); btn.type = "button";
    if (mode === "daily") { btn.textContent = "Practice mode"; btn.addEventListener("click", function () { setMode("medium"); }); }
    else { btn.textContent = "New pair"; btn.addEventListener("click", deal); }
    actions.appendChild(btn);
    if (mode === "daily") addShareBtn(actions);
    els.banner.appendChild(title); els.banner.appendChild(sub); els.banner.appendChild(actions);
    if (mode !== "daily") {
      var hint = document.createElement("div"); hint.className = "banner-hint";
      hint.textContent = "or just press Space for the next pair";
      els.banner.appendChild(hint);
    }
    els.banner.hidden = false;
  }

  // --- Autocomplete (careers pool minus the chain) ------------------------------
  function closeDropdown() {
    els.dropdown.hidden = true; els.dropdown.innerHTML = ""; matches = []; activeIndex = -1;
    els.input.setAttribute("aria-expanded", "false"); els.input.removeAttribute("aria-activedescendant");
  }
  function optionHTML(name) {
    return "<span class='opt-avatar' style='background:" + avatarColor(name) + "'>" + initials(name) + "</span>" +
      "<span class='opt-name'>" + name + "</span>";
  }
  function renderDropdown() {
    els.dropdown.innerHTML = "";
    if (!matches.length) {
      if (els.input.value.trim()) {
        var q = els.input.value.trim();
        var empty = document.createElement("div"); empty.className = "dropdown-empty";
        empty.textContent = chain.some(function (n) { return norm(n) === norm(q); })
          ? "Already in your chain — each player counts once" : "No player found — try another spelling";
        els.dropdown.appendChild(empty); els.dropdown.hidden = false; els.input.setAttribute("aria-expanded", "true");
      } else closeDropdown();
      return;
    }
    matches.forEach(function (name, i) {
      var item = document.createElement("div");
      item.className = "option" + (i === activeIndex ? " active" : "");
      item.id = "pb-opt-" + i; item.setAttribute("role", "option");
      item.setAttribute("aria-selected", i === activeIndex ? "true" : "false");
      item.innerHTML = optionHTML(name);
      item.addEventListener("pointerdown", function (e) { e.preventDefault(); submitGuess(name); });
      els.dropdown.appendChild(item);
    });
    els.dropdown.hidden = false; els.input.setAttribute("aria-expanded", "true");
    els.input.setAttribute("aria-activedescendant", activeIndex >= 0 ? "pb-opt-" + activeIndex : "");
  }
  function refreshMatches() {
    if (over) { closeDropdown(); return; }
    var q = norm(els.input.value.trim());
    if (!q) { closeDropdown(); return; }
    var used = {};
    chain.forEach(function (n) { used[n] = 1; });
    matches = CAREERS.map(function (c) { return c.name; })
      .filter(function (n) { return !used[n] && norm(n).indexOf(q) !== -1; })
      .slice(0, 8);
    activeIndex = matches.length ? 0 : -1;
    renderDropdown();
  }

  // --- Game flow -----------------------------------------------------------------
  function hasMove() {               // any unused teammate of the current end?
    var used = {};
    chain.forEach(function (n) { used[n] = 1; });
    return teammates(end()).some(function (n) { return !used[n]; });
  }
  function saveDaily() {
    lsSet(K.daily(dayKey), { puzzle: pIdx, chain: chain, left: left, wrong: wrong, done: over, won: won });
  }
  function finish(deadEnd) {
    over = true;
    els.input.disabled = true; closeDropdown();
    if (mode === "daily") { recordDaily(won); saveDaily(); } else record(won);
    renderChain(); renderStats(); updateCounter(); showBanner(deadEnd);
    if (els.sr) els.sr.textContent = won ? "Connected in " + steps() + " steps!" : "Not connected. The round is over.";
  }
  function submitGuess(name) {
    if (over || !name || !universe()[name]) return;
    if (chain.indexOf(name) >= 0) { flash("↺ " + name + " is already in your chain"); return; }   // free — no guess burned
    els.input.value = ""; closeDropdown();
    var l = link(end(), name);
    left--;
    if (l) {
      chain.push(name); misses = [];
      flash("");
      if (els.sr) els.sr.textContent = name + " linked via " + linkLabel(l) + ".";
      if (name === target) { won = true; finish(); return; }
      if (left <= 0) { won = false; finish(); return; }
      if (!hasMove()) { won = false; finish(true); return; }
      renderChain(); renderMisses();
    } else {
      wrong++;
      if (misses.indexOf(name) < 0) misses.push(name);
      flash("✗ " + name + " never shared a locker room with " + end() + " (in our data)");
      if (els.sr) els.sr.textContent = name + " never played with " + end() + ". " + left + " guesses left.";
      if (left <= 0) { won = false; finish(); return; }
      renderMisses();
    }
    if (mode === "daily") saveDaily();
    updateCounter();
    if (!over) els.input.focus();
  }
  function giveUp() {
    if (over || mode === "daily") return;
    won = false; finish();
  }

  function resetState() {
    chain = [start]; left = par + SLACK; wrong = 0; misses = []; over = false; won = false;
    els.input.value = ""; els.input.disabled = false; els.banner.hidden = true; flash("");
  }
  function applyPuzzle(i) {
    pIdx = i;
    var p = PATHS[pIdx];
    start = p.a; target = p.b; par = p.par; dealt = true;
  }
  function dealDaily() {
    var i = dailyIdx();
    if (i < 0) { els.counter.textContent = "No pairs available."; return; }
    applyPuzzle(i);
    resetState();
    var saved = lsGet(K.daily(dayKey), null);
    if (saved && saved.puzzle === pIdx && saved.chain && saved.chain[0] === start) {
      chain = saved.chain.slice();
      left = typeof saved.left === "number" ? saved.left : left;
      wrong = saved.wrong || 0;
      over = !!saved.done; won = !!saved.won;
    }
    renderChain(); renderMisses(); closeDropdown(); updateButtons();
    if (over) { els.input.disabled = true; showBanner(); updateCounter(); }
    else { updateCounter(); els.input.focus(); }
  }
  function deal() {
    if (mode === "daily") { dealDaily(); return; }
    var pool = pools()[BAND[mode]] || [];
    if (!pool.length) { els.counter.textContent = "No pairs for this mode."; return; }
    var i = pool[Math.floor(Math.random() * pool.length)];
    if (pool.length > 1 && i === pIdx) i = pool[(pool.indexOf(i) + 1) % pool.length];
    applyPuzzle(i);
    resetState();
    renderChain(); renderMisses(); updateCounter(); updateButtons(); closeDropdown(); els.input.focus();
  }

  function setMode(m) {
    mode = ({ daily: 1, easy: 1, medium: 1, hard: 1 })[m] ? m : "daily";
    if (mode === "daily") { dayKey = pendingArchive || todayStr(); isArchive = !!pendingArchive; pendingArchive = null; }
    lsSet(K.mode, mode);
    [["daily", els.tabDaily], ["easy", els.tabEasy], ["medium", els.tabMedium], ["hard", els.tabHard]].forEach(function (pr) {
      if (!pr[1]) return;
      var sel = pr[0] === mode;
      pr[1].classList.toggle("active", sel);
      pr[1].setAttribute("aria-selected", sel ? "true" : "false");
      pr[1].tabIndex = sel ? 0 : -1;
    });
    renderStats(); deal();
  }

  // --- How-to modal ----------------------------------------------------------------
  var lastFocus = null;
  function openInfo() {
    if (!els.infoModal) return;
    lsSet(K.seen, true);
    lastFocus = document.activeElement;
    els.infoModal.hidden = false;
    var d = els.infoModal.firstElementChild; if (d && d.focus) d.focus();
  }
  function closeInfo() {
    if (!els.infoModal) return;
    els.infoModal.hidden = true;
    if (lastFocus && lastFocus.focus) lastFocus.focus();
    lastFocus = null;
  }
  function maybeFirstHelp() {
    if (lsGet(K.seen, false)) return false;
    openInfo();
    return true;
  }
  function onModalKey(e) {
    if (!els.infoModal || els.infoModal.hidden) return;
    if (e.key === "Escape") { if (e.preventDefault) e.preventDefault(); closeInfo(); return; }
    if (e.key !== "Tab") return;
    var dlg = els.infoModal.firstElementChild; if (!dlg) return;
    var f = dlg.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');
    if (!f.length) return;
    var first = f[0], last = f[f.length - 1];
    if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
    else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
  }

  // --- Events / init -----------------------------------------------------------------
  function onKeyDown(e) {
    if (els.dropdown.hidden) return;
    if (!matches.length) { if (e.key === "Escape") closeDropdown(); return; }
    if (e.key === "ArrowDown") { e.preventDefault(); activeIndex = (activeIndex + 1) % matches.length; renderDropdown(); }
    else if (e.key === "ArrowUp") { e.preventDefault(); activeIndex = (activeIndex - 1 + matches.length) % matches.length; renderDropdown(); }
    else if (e.key === "Enter") { e.preventDefault(); if (activeIndex >= 0 && matches[activeIndex]) submitGuess(matches[activeIndex]); }
    else if (e.key === "Escape") closeDropdown();
  }
  function onModeKey(e) {
    var order = ["daily", "easy", "medium", "hard"], i = order.indexOf(mode), n = order.length, next = null;
    if (e.key === "ArrowRight" || e.key === "ArrowDown") next = order[(i + 1) % n];
    else if (e.key === "ArrowLeft" || e.key === "ArrowUp") next = order[(i + n - 1) % n];
    else if (e.key === "Home") next = order[0];
    else if (e.key === "End") next = order[n - 1];
    if (!next) return;
    e.preventDefault(); setMode(next);
    ({ daily: els.tabDaily, easy: els.tabEasy, medium: els.tabMedium, hard: els.tabHard })[next].focus();
  }
  function onGlobalKey(e) {
    if (els.infoModal && !els.infoModal.hidden) return;
    if (!over || mode === "daily") return;
    if (e.key !== " " && e.code !== "Space" && e.keyCode !== 32) return;
    if (els.view && els.view.hidden) return;
    var t = e.target;
    if (t && t.tagName && t.tagName.toUpperCase() === "BUTTON") return;
    if (e.preventDefault) e.preventDefault();
    deal();
  }

  function init() {
    els.input = $("pb-input"); els.dropdown = $("pb-dropdown"); els.chain = $("pb-chain");
    els.counter = $("pb-counter"); els.banner = $("pb-banner"); els.flash = $("pb-flash");
    els.guesses = $("pb-guesses"); els.next = $("pb-next"); els.giveup = $("pb-giveup");
    els.stats = $("pb-stats"); els.sr = $("pb-sr"); els.modeRow = $("pb-modes");
    els.tabDaily = $("pb-daily"); els.tabEasy = $("pb-easy"); els.tabMedium = $("pb-medium"); els.tabHard = $("pb-hard");
    els.view = $("pathbetween-view");
    els.infoBtn = $("pb-info-btn"); els.infoModal = $("pb-info-modal"); els.infoClose = $("pb-info-close");
    if (!els.input || !PATHS.length || !CAREERS.length) return;

    els.input.addEventListener("input", refreshMatches);
    els.input.addEventListener("keydown", onKeyDown);
    els.input.addEventListener("focus", refreshMatches);
    document.addEventListener("click", function (e) { if (e.target !== els.input && els.dropdown && !els.dropdown.contains(e.target)) closeDropdown(); });
    els.next.addEventListener("click", deal);
    if (els.giveup) els.giveup.addEventListener("click", giveUp);
    els.tabDaily.addEventListener("click", function () { if (mode !== "daily" || isArchive) setMode("daily"); });
    els.tabEasy.addEventListener("click", function () { if (mode !== "easy") setMode("easy"); });
    els.tabMedium.addEventListener("click", function () { if (mode !== "medium") setMode("medium"); });
    els.tabHard.addEventListener("click", function () { if (mode !== "hard") setMode("hard"); });
    if (els.modeRow) els.modeRow.addEventListener("keydown", onModeKey);
    if (els.infoBtn) els.infoBtn.addEventListener("click", openInfo);
    if (els.infoClose) els.infoClose.addEventListener("click", closeInfo);
    if (els.infoModal) els.infoModal.addEventListener("click", function (e) { if (e.target === els.infoModal) closeInfo(); });
    document.addEventListener("keydown", onModalKey);
    document.addEventListener("keydown", onGlobalKey);

    setMode(lsGet(K.mode, "daily"));
  }

  window.PathBetween = {
    onShow: function () { if (isArchive) setMode("daily"); else if (!dealt) deal(); if (maybeFirstHelp()) return; if (els.input && !over) els.input.focus(); },   // a hub open always lands on TODAY's edition
    goDaily: function () { setMode("daily"); },
    goPractice: function () { setMode("medium"); },
    goArchive: function (d) { pendingArchive = /^\d{4}-\d{2}-\d{2}$/.test(String(d)) ? String(d) : null; setMode("daily"); },
    // internal hooks used by test.js AND build_paths.js (shared teammate graph)
    _peek: function () { return { mode: mode, day: dayKey, archive: isArchive, pIdx: pIdx, a: start, b: target, par: par, chain: chain, left: left, wrong: wrong, over: over, won: won, misses: misses }; },
    _deal: deal,
    _setMode: setMode,
    _guess: submitGuess,
    _shareText: shareText,
    _link: link,
    _teammates: teammates,
    _bfs: bfs,
    _route: route,
    _universe: universe,
    _pools: pools
  };

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();
})();
