/* Six of a Kind — one category, six names. Each puzzle is two of The Grid's
 * criteria joined into one question ("Serbian players who played for FC
 * Barcelona"); name any SIX players who fit it. Three wrong names and it's over.
 * Modes: Daily (date-seeded, streak) + Practice (random).
 * Categories = window.SIXES (sixes.js, generated by build_sixes.js). Guesses are
 * judged by The Grid's own predicates (window.TheGrid._fits/_answers), so the
 * generator, The Grid and this game share ONE definition of "played for X".
 * Self-contained IIFE; exposes window.SixOfAKind. */
(function () {
  "use strict";

  var SIXES = window.SIXES || [];
  var GRID = window.TheGrid;
  var NEED = 6, STRIKES = 3;

  var K = {
    mode: "elg:sk:mode", stats: "elg:sk:stats", dstats: "elg:sk:dstats",
    seen: "elg:sk:seenhelp",
    daily: function (d) { return "elg:sk:daily:" + d; }
  };
  function lsGet(k, f) { try { var v = window.localStorage.getItem(k); return v == null ? f : JSON.parse(v); } catch (e) { return f; } }
  function lsSet(k, v) { try { window.localStorage.setItem(k, JSON.stringify(v)); } catch (e) {} }
  function norm(s) { return String(s).toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, ""); }
  function esc(s) { return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }

  function pad(n) { return n < 10 ? "0" + n : "" + n; }
  function dateStr(d) { return d.getFullYear() + "-" + pad(d.getMonth() + 1) + "-" + pad(d.getDate()); }
  function todayStr() { return dateStr(new Date()); }
  function yesterdayStr() { var d = new Date(); d.setDate(d.getDate() - 1); return dateStr(d); }
  function hashStr(s) { var h = 2166136261 >>> 0; for (var i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }

  function initials(name) { var p = String(name).trim().split(/\s+/); return ((p[0] || "")[0] || "") + ((p[1] || "")[0] || ""); }
  function avatarColor(name) { var h = 0; for (var i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) >>> 0; return "hsl(" + (h % 360) + ",45%,42%)"; }

  // --- The question, in words ----------------------------------------------------
  // Nationality values are countries (the national team a player plays for);
  // the clue reads better as the adjective. test.js checks every nationality
  // in the bank has one here.
  var DEMONYM = {
    Argentina: "Argentine", Canada: "Canadian", Croatia: "Croatian", France: "French", Germany: "German",
    Greece: "Greek", Israel: "Israeli", Italy: "Italian", Lithuania: "Lithuanian", Nigeria: "Nigerian",
    Russia: "Russian", Senegal: "Senegalese", Serbia: "Serbian", Slovenia: "Slovenian", Spain: "Spanish",
    Turkey: "Turkish", USA: "American"
  };
  function demonym(n) { return DEMONYM[n] || n; }
  function b(s) { return "<b>" + esc(s) + "</b>"; }
  function clueHTML(p) {
    var a = p.a, c = p.b;
    if (a.t === "club" && c.t === "club") return "Played for both " + b(a.v) + " and " + b(c.v);
    if (a.t === "club" && c.t === "nat") return b(demonym(c.v)) + " players who played for " + b(a.v);
    if (a.t === "club" && c.t === "pos") return b(c.v + "s") + " who played for " + b(a.v);
    if (a.t === "nat" && c.t === "pos") return b(demonym(a.v) + " " + c.v.toLowerCase() + "s");
    return b(a.v) + " + " + b(c.v);
  }
  function clueText(p) { return clueHTML(p).replace(/<[^>]+>/g, ""); }

  var els = {};
  function $(id) { return document.getElementById(id); }

  var mode = "daily";               // "daily" | "practice"
  var dayKey = todayStr();          // the date the Daily engine is playing (Archive replays a past one)
  var isArchive = false, pendingArchive = null;
  var puzzle = null, pIdx = -1, answers = [];
  var found = [], misses = [], over = false, won = false, dealt = false;
  var giveArmed = false, giveTimer = null;
  var matches = [], activeIndex = -1;

  function modeLabel() { return mode === "daily" ? (isArchive ? "Archive " + dayKey : "Daily") : "Practice"; }
  function dailyIdx() { return SIXES.length ? hashStr("six:" + dayKey) % SIXES.length : -1; }
  function strikesLeft() { return STRIKES - misses.length; }

  // --- Stats: practice (simple) + daily (streak) -----------------------------
  function defaultStats() { return { played: 0, solved: 0, curStreak: 0, maxStreak: 0 }; }
  function getStats() { return lsGet(K.stats, null) || defaultStats(); }
  function record(winFlag) {
    var s = getStats(); s.played++;
    if (winFlag) { s.solved++; s.curStreak++; if (s.curStreak > s.maxStreak) s.maxStreak = s.curStreak; } else s.curStreak = 0;
    lsSet(K.stats, s); return s;
  }
  function defaultDStats() { return { played: 0, solved: 0, curStreak: 0, maxStreak: 0, lastDate: null, lastWon: false }; }
  function getDStats() { return lsGet(K.dstats, null) || defaultDStats(); }
  function recordDaily(winFlag) {
    var s = getDStats();
    if (isArchive) return s;                   // archive replays never touch streaks
    if (s.lastDate === todayStr()) return s;
    s.played++;
    if (winFlag) { s.solved++; s.curStreak = (s.lastDate === yesterdayStr() && s.lastWon) ? s.curStreak + 1 : 1; if (s.curStreak > s.maxStreak) s.maxStreak = s.curStreak; }
    else s.curStreak = 0;
    s.lastDate = todayStr(); s.lastWon = winFlag;
    lsSet(K.dstats, s); return s;
  }
  function renderStats() {
    if (!els.stats) return;
    if (mode === "daily") {
      var s = getDStats();
      var live = (s.lastDate === todayStr() || s.lastDate === yesterdayStr()) ? s.curStreak : 0;
      els.stats.textContent = "Daily · Solved " + s.solved + "/" + s.played + " · Streak " + live + " · Best " + s.maxStreak;
    } else {
      var p = getStats();
      els.stats.textContent = "Solved " + p.solved + "/" + p.played + " · Streak " + p.curStreak + " · Best " + p.maxStreak;
    }
  }

  // --- Rendering -------------------------------------------------------------
  function renderClue() {
    els.clue.innerHTML = clueHTML(puzzle);
    els.count.textContent = answers.length + " players in our data fit — name any six.";
  }
  function renderSlots() {
    els.slots.innerHTML = "";
    for (var i = 0; i < NEED; i++) {
      var s = document.createElement("div");
      var n = found[i];
      s.className = "sk-slot" + (n ? " filled" : "");
      s.textContent = n || String(i + 1);
      els.slots.appendChild(s);
    }
  }
  function renderStrikes() {
    els.strikes.innerHTML = "";
    for (var i = 0; i < STRIKES; i++) {
      var p = document.createElement("span");
      p.className = "sk-strike" + (i < misses.length ? " used" : "");
      p.textContent = i < misses.length ? "✗" : "";
      els.strikes.appendChild(p);
    }
    els.strikes.setAttribute("aria-label", strikesLeft() + " of " + STRIKES + " misses left");
  }
  function renderMisses() {
    if (!els.misses) return;
    els.misses.textContent = misses.length ? "Not in it: " + misses.join(", ") : "";
    els.misses.hidden = !misses.length;
  }
  function updateCounter() {
    if (over) { els.counter.textContent = modeLabel() + " · " + (won ? "Six of a kind! 🎉" : found.length + "/" + NEED + " named"); return; }
    var left = strikesLeft();
    els.counter.textContent = modeLabel() + " · " + found.length + "/" + NEED + " named · " +
      left + (left === 1 ? " miss left — careful!" : " misses left");
  }
  function updateNextBtn() {
    if (els.next) els.next.style.display = (mode === "daily") ? "none" : "";   // one category a day
    if (els.giveup) els.giveup.style.display = over ? "none" : "";
  }
  function flash(msg, cls) { if (els.flash) { els.flash.textContent = msg; els.flash.className = "sk-flash" + (cls ? " " + cls : ""); els.flash.hidden = !msg; } }
  function paint() { renderSlots(); renderStrikes(); renderMisses(); updateCounter(); updateNextBtn(); }

  // Every name that fit, yours first — the end-of-game list is the payoff, the
  // part that teaches you the ones you forgot.
  function renderAnswers() {
    els.answers.innerHTML = "";
    var mine = {}; found.forEach(function (n) { mine[n] = 1; });
    var rest = answers.filter(function (n) { return !mine[n]; }).sort();
    var h = document.createElement("div"); h.className = "sk-answers-head";
    h.textContent = won ? "The other " + rest.length + " who fit" : "All " + answers.length + " who fit";
    els.answers.appendChild(h);
    var list = document.createElement("div"); list.className = "sk-answers-list";
    found.concat(rest).forEach(function (n) {
      var c = document.createElement("span");
      c.className = "sk-ans" + (mine[n] ? " mine" : "");
      c.textContent = n;
      list.appendChild(c);
    });
    els.answers.appendChild(list);
    els.answers.hidden = false;
  }

  function dailyBannerNote() {
    if (mode !== "daily") return "";
    if (isArchive) return "<br>That was the " + dayKey + " edition.";
    if (!won) return "<br>A new category lands at midnight — come back for revenge!";
    var s = getDStats();
    return s.curStreak >= 2 ? "<br>🔥 <strong>" + s.curStreak + "-day streak</strong> — see you tomorrow!"
                            : "<br>Come back tomorrow for a new category. 👋";
  }
  function shareText() {
    var row = "";
    for (var i = 0; i < NEED; i++) row += i < found.length ? "🟩" : "⬛";
    var tail = won ? (misses.length ? " · " + misses.length + (misses.length === 1 ? " miss" : " misses") : " · no misses") : " · " + found.length + "/" + NEED;
    return "Six of a Kind 🏀 " + dayKey + "\n" + clueText(puzzle) + "\n" + row + tail +
      (window.ELG ? "\n" + window.ELG.shareURL("sixofakind") : "");
  }
  function addShareBtn(actions) {
    var btn = document.createElement("button"); btn.type = "button"; btn.className = "share-btn alt";
    btn.textContent = "Share result";
    btn.addEventListener("click", function () { if (window.ELG) window.ELG.copyShare(shareText(), btn); });
    actions.appendChild(btn);
  }
  function showBanner() {
    els.banner.className = "banner " + (won ? "win" : "lose");
    els.banner.innerHTML = "";
    var title = document.createElement("div"); title.className = "banner-title";
    title.textContent = won ? (misses.length === 0 ? "🤩 Six of a kind, no misses!" : "🏆 Six of a kind!") : "😔 " + found.length + " of a kind…";
    var sub = document.createElement("div"); sub.className = "banner-sub";
    sub.innerHTML = (won ? "All six named" + (misses.length ? ", " + misses.length + (misses.length === 1 ? " miss" : " misses") + " along the way." : " without a single miss.")
                         : "You named <strong>" + found.length + "/" + NEED + "</strong>. Here's everyone who fit.") +
      dailyBannerNote();
    var actions = document.createElement("div"); actions.className = "banner-actions";
    var btn = document.createElement("button"); btn.type = "button";
    if (mode === "daily") { btn.textContent = "Practice mode"; btn.addEventListener("click", function () { setMode("practice"); }); }
    else { btn.textContent = "New category"; btn.addEventListener("click", deal); }
    actions.appendChild(btn);
    if (mode === "daily") addShareBtn(actions);
    els.banner.appendChild(title); els.banner.appendChild(sub); els.banner.appendChild(actions);
    if (mode !== "daily") {
      var hint = document.createElement("div"); hint.className = "banner-hint";
      hint.textContent = "or just press Space for the next category";
      els.banner.appendChild(hint);
    }
    els.banner.hidden = false;
    renderAnswers();
  }

  // --- Autocomplete ----------------------------------------------------------
  // The list is EVERY player The Grid can judge, not just the ones who fit: it
  // spells names for you, it never tells you who is in the category.
  var NAMES = null;
  function namePool() {
    if (NAMES) return NAMES;
    var u = GRID._universe(); NAMES = [];
    for (var n in u) NAMES.push({ name: n });
    NAMES.sort(function (x, y) { return x.name < y.name ? -1 : 1; });
    return NAMES;
  }
  function tried(name) { return found.indexOf(name) >= 0 || misses.indexOf(name) >= 0; }
  function closeDropdown() {
    els.dropdown.hidden = true; els.dropdown.innerHTML = ""; matches = []; activeIndex = -1;
    els.input.setAttribute("aria-expanded", "false"); els.input.removeAttribute("aria-activedescendant");
  }
  function optionHTML(p) {
    return "<span class='opt-avatar' style='background:" + avatarColor(p.name) + "'>" + initials(p.name) + "</span>" +
      "<span class='opt-name'>" + esc(p.name) + "</span>";
  }
  function renderDropdown() {
    els.dropdown.innerHTML = "";
    if (!matches.length) {
      if (els.input.value.trim()) {
        var empty = document.createElement("div"); empty.className = "dropdown-empty";
        empty.textContent = "No player found — try another spelling";
        els.dropdown.appendChild(empty); els.dropdown.hidden = false; els.input.setAttribute("aria-expanded", "true");
      } else closeDropdown();
      return;
    }
    matches.forEach(function (p, i) {
      var item = document.createElement("div");
      item.className = "option" + (i === activeIndex ? " active" : "");
      item.id = "sk-opt-" + i; item.setAttribute("role", "option");
      item.setAttribute("aria-selected", i === activeIndex ? "true" : "false");
      item.innerHTML = optionHTML(p);
      item.addEventListener("pointerdown", function (e) { e.preventDefault(); submitGuess(p.name); });
      els.dropdown.appendChild(item);
    });
    els.dropdown.hidden = false; els.input.setAttribute("aria-expanded", "true");
    els.input.setAttribute("aria-activedescendant", activeIndex >= 0 ? "sk-opt-" + activeIndex : "");
  }
  function refreshMatches() {
    if (over) { closeDropdown(); return; }
    var q = norm(els.input.value.trim());
    if (!q) { closeDropdown(); return; }
    matches = namePool().filter(function (p) { return !tried(p.name) && norm(p.name).indexOf(q) !== -1; }).slice(0, 8);
    activeIndex = matches.length ? 0 : -1;
    renderDropdown();
  }

  // --- Game flow -------------------------------------------------------------
  function saveDaily() {
    lsSet(K.daily(dayKey), { puzzle: pIdx, cat: puzzle, found: found, misses: misses, done: over, won: won });
  }
  function finish() {
    over = true;
    disarmGiveUp();
    els.input.disabled = true; els.input.value = ""; closeDropdown();
    if (mode === "daily") { recordDaily(won); saveDaily(); } else record(won);
    paint(); renderStats(); showBanner();
    if (els.sr) els.sr.textContent = won ? "Six of a kind!" : "Game over. " + found.length + " of six named.";
  }
  function submitGuess(name) {
    if (over || !name) return;
    disarmGiveUp();                    // playing on withdraws a half-pressed concession
    if (tried(name)) { flash("↺ You've already tried " + name, "err"); return; }   // free — no miss burned
    els.input.value = ""; closeDropdown();
    if (answers.indexOf(name) >= 0) {
      found.push(name);
      flash("✓ " + name, "ok");
      if (els.sr) els.sr.textContent = name + " fits. " + found.length + " of six.";
      if (found.length >= NEED) { won = true; finish(); return; }
    } else {
      misses.push(name);
      flash("✗ " + name + " doesn't fit", "err");
      if (els.sr) els.sr.textContent = name + " doesn't fit. " + strikesLeft() + " misses left.";
      if (misses.length >= STRIKES) { won = false; finish(); return; }
    }
    if (mode === "daily") saveDaily();
    paint();
    els.input.focus();
  }
  function disarmGiveUp() {
    giveArmed = false;
    if (giveTimer) { clearTimeout(giveTimer); giveTimer = null; }
    if (els.giveup) { els.giveup.textContent = "Give up"; els.giveup.classList.remove("armed"); }
  }
  // As in The Grid: the Daily asks once (Sure?) because the loss is written at
  // once and there's no second category today; a lost daily still counts as
  // played, so the hub streak survives. Practice concedes in one tap.
  function giveUp() {
    if (over) return;
    if (mode === "daily" && !giveArmed) {
      giveArmed = true;
      if (els.giveup) { els.giveup.textContent = "Sure?"; els.giveup.classList.add("armed"); }
      giveTimer = setTimeout(disarmGiveUp, 3000);
      return;
    }
    won = false; finish();
  }

  function resetState() {
    found = []; misses = []; over = false; won = false;
    disarmGiveUp();
    els.input.value = ""; els.input.disabled = false;
    els.banner.hidden = true; els.answers.hidden = true; els.answers.innerHTML = ""; flash("");
  }
  function begin() {
    answers = GRID._answers(puzzle.a, puzzle.b);
    dealt = true;
    renderClue(); closeDropdown();
  }
  function dealDaily() {
    pIdx = dailyIdx();
    if (pIdx < 0) { els.counter.textContent = "No categories available."; return; }
    puzzle = SIXES[pIdx];
    resetState();
    var saved = lsGet(K.daily(dayKey), null);
    // A save keeps its own category, so a regenerated bank can never re-ask a
    // daily someone has already played (the lesson of Career Order's saves).
    if (saved && saved.cat && saved.cat.a && saved.cat.b) puzzle = saved.cat;
    else if (saved && saved.puzzle !== pIdx) saved = null;
    begin();
    if (saved) {
      found = (saved.found || []).filter(function (n) { return answers.indexOf(n) >= 0; }).slice(0, NEED);
      misses = (saved.misses || []).slice(0, STRIKES);
      over = !!saved.done; won = !!saved.won;
    }
    paint();
    if (over) { els.input.disabled = true; showBanner(); }
  }
  function deal() {
    if (mode === "daily") { dealDaily(); return; }
    if (!SIXES.length) { els.counter.textContent = "No categories available."; return; }
    var i = Math.floor(Math.random() * SIXES.length);
    if (SIXES.length > 1 && i === pIdx) i = (i + 1) % SIXES.length;
    pIdx = i; puzzle = SIXES[pIdx];
    resetState(); begin(); paint();
    if (els.input && els.view && !els.view.hidden) els.input.focus();
  }

  function setMode(m) {
    mode = (m === "practice") ? "practice" : "daily";
    if (mode === "daily") { dayKey = pendingArchive || todayStr(); isArchive = !!pendingArchive; pendingArchive = null; }
    lsSet(K.mode, mode);
    if (window.ELG && window.ELG.modeURL) window.ELG.modeURL("sixofakind", mode);   // keep ?mode= honest
    [["daily", els.tabDaily], ["practice", els.tabPractice]].forEach(function (pr) {
      if (!pr[1]) return;
      var sel = pr[0] === mode;
      pr[1].classList.toggle("active", sel);
      pr[1].setAttribute("aria-selected", sel ? "true" : "false");
      pr[1].tabIndex = sel ? 0 : -1;
    });
    renderStats(); deal();
  }

  // --- How-to modal ----------------------------------------------------------
  var lastFocus = null;
  function openInfo() {
    if (!els.infoModal) return;
    lsSet(K.seen, true);
    lastFocus = document.activeElement;
    els.infoModal.hidden = false;
    var d = els.infoModal.firstElementChild; if (d && d.focus) d.focus();
  }
  function closeInfo() {
    if (!els.infoModal) return;
    els.infoModal.hidden = true;
    if (lastFocus && lastFocus.focus) lastFocus.focus();
    lastFocus = null;
  }
  function maybeFirstHelp() {
    if (lsGet(K.seen, false)) return false;
    openInfo();
    return true;
  }
  function onModalKey(e) {
    if (!els.infoModal || els.infoModal.hidden) return;
    if (e.key === "Escape") { if (e.preventDefault) e.preventDefault(); closeInfo(); return; }
    if (e.key !== "Tab") return;
    var dlg = els.infoModal.firstElementChild; if (!dlg) return;
    var f = dlg.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');
    if (!f.length) return;
    var first = f[0], last = f[f.length - 1];
    if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
    else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
  }

  // --- Events / init ---------------------------------------------------------
  function onKeyDown(e) {
    if (els.dropdown.hidden) return;
    if (!matches.length) { if (e.key === "Escape") closeDropdown(); return; }
    if (e.key === "ArrowDown") { e.preventDefault(); activeIndex = (activeIndex + 1) % matches.length; renderDropdown(); }
    else if (e.key === "ArrowUp") { e.preventDefault(); activeIndex = (activeIndex - 1 + matches.length) % matches.length; renderDropdown(); }
    else if (e.key === "Enter") { e.preventDefault(); if (activeIndex >= 0 && matches[activeIndex]) submitGuess(matches[activeIndex].name); }
    else if (e.key === "Escape") closeDropdown();
  }
  function onModeKey(e) {
    var order = ["daily", "practice"], i = order.indexOf(mode), n = order.length, next = null;
    if (e.key === "ArrowRight" || e.key === "ArrowDown") next = order[(i + 1) % n];
    else if (e.key === "ArrowLeft" || e.key === "ArrowUp") next = order[(i + n - 1) % n];
    else if (e.key === "Home") next = order[0];
    else if (e.key === "End") next = order[n - 1];
    if (!next) return;
    e.preventDefault(); setMode(next);
    ({ daily: els.tabDaily, practice: els.tabPractice })[next].focus();
  }
  function onGlobalKey(e) {
    if (els.infoModal && !els.infoModal.hidden) return;
    if (!over || mode === "daily") return;
    if (e.key !== " " && e.code !== "Space" && e.keyCode !== 32) return;
    if (els.view && els.view.hidden) return;
    var t = e.target;
    if (t && t.tagName && t.tagName.toUpperCase() === "BUTTON") return;
    if (e.preventDefault) e.preventDefault();
    deal();
  }

  function init() {
    els.input = $("sk-input"); els.dropdown = $("sk-dropdown"); els.clue = $("sk-clue"); els.count = $("sk-count");
    els.slots = $("sk-slots"); els.strikes = $("sk-strikes"); els.misses = $("sk-misses"); els.answers = $("sk-answers");
    els.counter = $("sk-counter"); els.banner = $("sk-banner"); els.flash = $("sk-flash");
    els.next = $("sk-next"); els.giveup = $("sk-giveup"); els.stats = $("sk-stats"); els.sr = $("sk-sr");
    els.modeRow = $("sk-modes"); els.tabDaily = $("sk-daily"); els.tabPractice = $("sk-practice");
    els.view = $("sixofakind-view");
    els.infoBtn = $("sk-info-btn"); els.infoModal = $("sk-info-modal"); els.infoClose = $("sk-info-close");
    // EuroLeague only: the categories are built from its careers, and in the
    // EuroCup The Grid's predicates judge the EuroCup's players instead.
    if (window.ELG_COMP && window.ELG_COMP.id !== "euroleague") return;
    if (!els.input || !SIXES.length || !GRID) return;

    els.input.addEventListener("input", refreshMatches);
    els.input.addEventListener("keydown", onKeyDown);
    els.input.addEventListener("focus", refreshMatches);
    document.addEventListener("click", function (e) { if (e.target !== els.input && els.dropdown && !els.dropdown.contains(e.target)) closeDropdown(); });
    els.next.addEventListener("click", deal);
    if (els.giveup) els.giveup.addEventListener("click", giveUp);
    els.tabDaily.addEventListener("click", function () { if (mode !== "daily" || isArchive) setMode("daily"); });
    els.tabPractice.addEventListener("click", function () { if (mode !== "practice") setMode("practice"); });
    if (els.modeRow) els.modeRow.addEventListener("keydown", onModeKey);
    if (els.infoBtn) els.infoBtn.addEventListener("click", openInfo);
    if (els.infoClose) els.infoClose.addEventListener("click", closeInfo);
    if (els.infoModal) els.infoModal.addEventListener("click", function (e) { if (e.target === els.infoModal) closeInfo(); });
    document.addEventListener("keydown", onModalKey);
    document.addEventListener("keydown", onGlobalKey);

    setMode(lsGet(K.mode, "daily"));
  }

  window.SixOfAKind = {
    onShow: function () { if (isArchive) setMode("daily"); else if (!dealt) deal(); if (maybeFirstHelp()) return; if (els.input && !over) els.input.focus(); },   // a hub open always lands on TODAY's edition
    goDaily: function () { setMode("daily"); },
    goPractice: function () { setMode("practice"); },
    goMode: setMode,
    goArchive: function (d) { pendingArchive = /^\d{4}-\d{2}-\d{2}$/.test(String(d)) ? String(d) : null; setMode("daily"); },
    // internal hooks used by test.js
    _peek: function () { return { mode: mode, day: dayKey, archive: isArchive, pIdx: pIdx, puzzle: puzzle, answers: answers.slice(), found: found.slice(), misses: misses.slice(), over: over, won: won }; },
    _deal: deal,
    _setMode: setMode,
    _submit: submitGuess,
    _giveUp: giveUp,
    _shareText: shareText,
    _clue: clueText,
    _demonyms: DEMONYM
  };

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();
})();
