/* The Grid — Immaculate-Grid-style: a 3×3 board whose rows and columns are
 * criteria (clubs / nationalities / positions); fill every cell with a player
 * who fits BOTH. 12 guesses for 9 cells, every guess costs one, each player can
 * be used once. Modes: Daily (date-seeded, streak) + Practice (random).
 * Puzzles = window.GRIDS (grids.js, generated by build_grids.js — which loads
 * THIS file for its predicates, so generator and game can never disagree).
 * Self-contained IIFE; exposes window.TheGrid. */
(function () {
  "use strict";

  var PLAYERS = window.PLAYERS || [];
  var LEGENDS = window.LEGENDS || [];
  var CAREERS = window.CAREERS || [];
  var LINEUPS = window.LINEUPS || [];
  var MAX = 12;                      // guesses for the 9 cells

  var K = {
    mode: "elg:gr:mode", stats: "elg:gr:stats", dstats: "elg:gr:dstats",
    seen: "elg:gr:seenhelp",
    daily: function (d) { return "elg:gr:daily:" + d; }
  };
  function lsGet(k, f) { try { var v = window.localStorage.getItem(k); return v == null ? f : JSON.parse(v); } catch (e) { return f; } }
  function lsSet(k, v) { try { window.localStorage.setItem(k, JSON.stringify(v)); } catch (e) {} }
  function norm(s) { return String(s).toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, ""); }

  function pad(n) { return n < 10 ? "0" + n : "" + n; }
  function dateStr(d) { return d.getFullYear() + "-" + pad(d.getMonth() + 1) + "-" + pad(d.getDate()); }
  function todayStr() { return dateStr(new Date()); }
  function yesterdayStr() { var d = new Date(); d.setDate(d.getDate() - 1); return dateStr(d); }
  function hashStr(s) { var h = 2166136261 >>> 0; for (var i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }

  function initials(name) { var p = String(name).trim().split(/\s+/); return ((p[0] || "")[0] || "") + ((p[1] || "")[0] || ""); }
  function avatarColor(name) { var h = 0; for (var i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) >>> 0; return "hsl(" + (h % 360) + ",45%,42%)"; }

  // --- Player universe: only players whose FULL career we know ----------------
  // The Grid checks "played for club X" against our data, so it MUST only offer
  // players whose whole path we have — otherwise a genuinely-correct guess
  // (e.g. a current roster player who also played elsewhere years ago) gets
  // rejected because we only stored his current club. So the pool is the
  // careers.js players (the well-travelled veterans + legends), each enriched
  // with his current-roster and Final-Four clubs. Every offered name is then
  // accurately answerable, and cells still have several right answers.
  var UNIVERSE = null;
  function universe() {
    if (UNIVERSE) return UNIVERSE;
    var u = {};
    CAREERS.forEach(function (c) {
      var e = u[c.name] = { name: c.name, nat: c.nationality, pos: c.position, clubs: {} };
      c.career.forEach(function (s) { e.clubs[s.team] = 1; });
    });
    function addClub(name, team) { if (u[name]) u[name].clubs[team] = 1; }
    PLAYERS.forEach(function (p) { addClub(p.name, p.team); });
    LEGENDS.forEach(function (p) { addClub(p.name, p.team); });
    LINEUPS.forEach(function (L) { L.five.forEach(function (p) { addClub(p.name, L.team); }); });
    UNIVERSE = u;
    return u;
  }
  function fits(name, crit) {
    var e = universe()[name];
    if (!e) return false;
    if (crit.t === "club") return !!e.clubs[crit.v];
    if (crit.t === "nat") return e.nat === crit.v;
    if (crit.t === "pos") return e.pos === crit.v;
    return false;
  }
  function answers(a, b) {
    var u = universe(), out = [];
    for (var name in u) if (fits(name, a) && fits(name, b)) out.push(name);
    return out;
  }
  function critLabel(c) { return c.t === "pos" ? c.v + "s" : c.v; }

  var els = {};
  function $(id) { return document.getElementById(id); }

  var GRIDS = window.GRIDS || [];
  var mode = "daily";               // "daily" | "practice"
  var puzzle = null, pIdx = -1, cells = [], left = MAX, wrong = 0;
  var over = false, won = false, dealt = false, selected = -1, used = {};
  var misses = [];                  // per-cell list of names tried that didn't fit
  var cellEls = [];
  var matches = [], activeIndex = -1;

  function modeLabel() { return mode === "daily" ? "Daily" : "Practice"; }
  function dailyIdx() { return GRIDS.length ? hashStr("grid:" + todayStr()) % GRIDS.length : -1; }
  function critAt(i) { return { row: puzzle.rows[Math.floor(i / 3)], col: puzzle.cols[i % 3] }; }

  // --- Stats: practice (simple) + daily (streak) -----------------------------
  function defaultStats() { return { played: 0, solved: 0, curStreak: 0, maxStreak: 0 }; }
  function getStats() { return lsGet(K.stats, null) || defaultStats(); }
  function record(winFlag) {
    var s = getStats(); s.played++;
    if (winFlag) { s.solved++; s.curStreak++; if (s.curStreak > s.maxStreak) s.maxStreak = s.curStreak; } else s.curStreak = 0;
    lsSet(K.stats, s); return s;
  }
  function defaultDStats() { return { played: 0, solved: 0, curStreak: 0, maxStreak: 0, lastDate: null, lastWon: false }; }
  function getDStats() { return lsGet(K.dstats, null) || defaultDStats(); }
  function recordDaily(winFlag) {
    var s = getDStats();
    if (s.lastDate === todayStr()) return s;
    s.played++;
    if (winFlag) { s.solved++; s.curStreak = (s.lastDate === yesterdayStr() && s.lastWon) ? s.curStreak + 1 : 1; if (s.curStreak > s.maxStreak) s.maxStreak = s.curStreak; }
    else s.curStreak = 0;
    s.lastDate = todayStr(); s.lastWon = winFlag;
    lsSet(K.dstats, s); return s;
  }
  function renderStats() {
    if (!els.stats) return;
    if (mode === "daily") {
      var s = getDStats();
      var live = (s.lastDate === todayStr() || s.lastDate === yesterdayStr()) ? s.curStreak : 0;
      els.stats.textContent = "Daily · Solved " + s.solved + "/" + s.played + " · Streak " + live + " · Best " + s.maxStreak;
    } else {
      var p = getStats();
      els.stats.textContent = "Solved " + p.solved + "/" + p.played + " · Streak " + p.curStreak + " · Best " + p.maxStreak;
    }
  }

  // --- Rendering -------------------------------------------------------------
  function filledCount() { var n = 0; cells.forEach(function (c) { if (c && !c.revealed) n++; }); return n; }
  function cellText(i) {
    if (cells[i]) return cells[i].name;
    return "";
  }
  function paintCell(i) {
    var b = cellEls[i]; if (!b) return;
    b.textContent = cells[i] ? cells[i].name : "";
    b.classList.toggle("filled", !!cells[i] && !cells[i].revealed);
    b.classList.toggle("revealed", !!cells[i] && !!cells[i].revealed);
    b.classList.toggle("sel", i === selected);
    b.classList.toggle("tried", !cells[i] && !!(misses[i] && misses[i].length));
    b.disabled = over || !!cells[i];
    var c = critAt(i);
    b.setAttribute("aria-label", critLabel(c.row) + " + " + critLabel(c.col) + " — " +
      (cells[i] ? cells[i].name : (i === selected ? "selected" : "empty")));
  }
  function paintAll() { for (var i = 0; i < 9; i++) paintCell(i); }
  function renderBoard() {
    els.board.innerHTML = "";
    cellEls = [];
    var corner = document.createElement("div"); corner.className = "gr-corner"; els.board.appendChild(corner);
    puzzle.cols.forEach(function (c) {
      var h = document.createElement("div"); h.className = "gr-head"; h.textContent = critLabel(c); els.board.appendChild(h);
    });
    for (var r = 0; r < 3; r++) {
      var rh = document.createElement("div"); rh.className = "gr-head"; rh.textContent = critLabel(puzzle.rows[r]); els.board.appendChild(rh);
      for (var c = 0; c < 3; c++) {
        (function (i) {
          var b = document.createElement("button"); b.type = "button"; b.className = "gr-cell";
          b.addEventListener("click", function () { select(i); });
          cellEls[i] = b; els.board.appendChild(b);
        })(r * 3 + c);
      }
    }
    paintAll();
  }
  function updateCounter() {
    if (over) { els.counter.textContent = modeLabel() + " · " + (won ? "Solved! 🎉" : "Filled " + filledCount() + "/9"); return; }
    els.counter.textContent = modeLabel() + " · " + filledCount() + "/9 filled · " + left + (left === 1 ? " guess left — make it count!" : " guesses left");
  }
  function updateNextBtn() {
    if (els.next) els.next.style.display = (mode === "daily") ? "none" : "";
    if (els.giveup) els.giveup.style.display = (mode === "daily") ? "none" : "";
  }
  function flash(msg) { if (els.flash) { els.flash.textContent = msg; els.flash.hidden = !msg; } }

  function dailyBannerNote() {
    if (mode !== "daily") return "";
    if (!won) return "<br>A fresh grid lands at midnight — come back for revenge!";
    var s = getDStats();
    return s.curStreak >= 2 ? "<br>🔥 <strong>" + s.curStreak + "-day streak</strong> — see you tomorrow!"
                            : "<br>Come back tomorrow for a new grid. 👋";
  }
  function shareText() {
    var rows = [], r, c;
    for (r = 0; r < 3; r++) {
      var line = "";
      for (c = 0; c < 3; c++) { var cell = cells[r * 3 + c]; line += (cell && !cell.revealed) ? "🟩" : "⬛"; }
      rows.push(line);
    }
    var score = won ? "9/9" + (wrong ? " · " + wrong + (wrong === 1 ? " miss" : " misses") : " · immaculate") : filledCount() + "/9";
    return "The Grid 🏀 " + todayStr() + "\n" + score + "\n" + rows.join("\n") +
      (window.ELG ? "\n" + window.ELG.shareURL("thegrid") : "");
  }
  function addShareBtn(actions) {
    if (!actions) return;
    var b = document.createElement("button"); b.type = "button"; b.className = "share-btn alt";
    b.textContent = "Share result";
    b.addEventListener("click", function () { if (window.ELG) window.ELG.copyShare(shareText(), b); });
    actions.appendChild(b);
  }
  function showBanner() {
    els.banner.className = "banner " + (won ? "win" : "lose");
    els.banner.innerHTML = "";
    var title = document.createElement("div"); title.className = "banner-title";
    title.textContent = won ? (wrong === 0 ? "🤩 Immaculate!" : "🏆 Grid complete!") : "😔 The grid held out…";
    var sub = document.createElement("div"); sub.className = "banner-sub";
    sub.innerHTML = (won ? "All 9 cells, " + (wrong ? wrong + (wrong === 1 ? " miss" : " misses") + " along the way." : "not a single miss.")
                         : "You filled <strong>" + filledCount() + "/9</strong> — the empty cells show an answer that fit.") +
      dailyBannerNote();
    var actions = document.createElement("div"); actions.className = "banner-actions";
    var btn = document.createElement("button"); btn.type = "button";
    if (mode === "daily") { btn.textContent = "Practice mode"; btn.addEventListener("click", function () { setMode("practice"); }); }
    else { btn.textContent = "New grid"; btn.addEventListener("click", deal); }
    actions.appendChild(btn);
    if (mode === "daily") addShareBtn(actions);
    els.banner.appendChild(title); els.banner.appendChild(sub); els.banner.appendChild(actions);
    if (mode !== "daily") {
      var hint = document.createElement("div"); hint.className = "banner-hint";
      hint.textContent = "or just press Space for the next grid";
      els.banner.appendChild(hint);
    }
    els.banner.hidden = false;
  }

  // --- Autocomplete ----------------------------------------------------------
  var NAMES = null;
  function namePool() {
    if (NAMES) return NAMES;
    var u = universe(); NAMES = [];
    for (var n in u) NAMES.push({ name: n });
    NAMES.sort(function (a, b) { return a.name < b.name ? -1 : 1; });
    return NAMES;
  }
  function closeDropdown() {
    els.dropdown.hidden = true; els.dropdown.innerHTML = ""; matches = []; activeIndex = -1;
    els.input.setAttribute("aria-expanded", "false"); els.input.removeAttribute("aria-activedescendant");
  }
  function optionHTML(p) {
    return "<span class='opt-avatar' style='background:" + avatarColor(p.name) + "'>" + initials(p.name) + "</span>" +
      "<span class='opt-name'>" + p.name + "</span>";
  }
  function renderDropdown() {
    els.dropdown.innerHTML = "";
    if (!matches.length) {
      if (els.input.value.trim()) {
        var empty = document.createElement("div"); empty.className = "dropdown-empty";
        empty.textContent = used[norm(els.input.value.trim())] ? "Already on the board — each player counts once" : "No player found — try another spelling";
        els.dropdown.appendChild(empty); els.dropdown.hidden = false; els.input.setAttribute("aria-expanded", "true");
      } else closeDropdown();
      return;
    }
    matches.forEach(function (p, i) {
      var item = document.createElement("div");
      item.className = "option" + (i === activeIndex ? " active" : "");
      item.id = "gr-opt-" + i; item.setAttribute("role", "option");
      item.setAttribute("aria-selected", i === activeIndex ? "true" : "false");
      item.innerHTML = optionHTML(p);
      item.addEventListener("pointerdown", function (e) { e.preventDefault(); submitGuess(p.name); });
      els.dropdown.appendChild(item);
    });
    els.dropdown.hidden = false; els.input.setAttribute("aria-expanded", "true");
    els.input.setAttribute("aria-activedescendant", activeIndex >= 0 ? "gr-opt-" + activeIndex : "");
  }
  function refreshMatches() {
    if (over || selected < 0) { closeDropdown(); return; }
    var q = norm(els.input.value.trim());
    if (!q) { closeDropdown(); return; }
    var seen = {};
    matches = namePool().filter(function (p) {
      if (seen[p.name] || used[p.name] || norm(p.name).indexOf(q) === -1) return false;
      seen[p.name] = 1; return true;
    }).slice(0, 8);
    activeIndex = matches.length ? 0 : -1;
    renderDropdown();
  }

  // --- Game flow -------------------------------------------------------------
  function showCellMisses(i) {          // remind the player what they've already tried here
    var m = misses[i] || [];
    flash(m.length ? "✗ Already tried here: " + m.join(", ") : "");
  }
  function select(i) {
    if (over || cells[i]) return;
    selected = i;
    paintAll();
    showCellMisses(i);
    if (els.input) { els.input.disabled = false; els.input.focus(); }
  }
  function autoSelect() {                          // next empty cell, if any
    selected = -1;
    for (var i = 0; i < 9; i++) if (!cells[i]) { selected = i; break; }
    paintAll();
  }
  function saveDaily() {
    lsSet(K.daily(todayStr()), {
      puzzle: pIdx,
      cells: cells.map(function (c) { return c && !c.revealed ? c.name : null; }),
      misses: misses, left: left, wrong: wrong, done: over, won: won
    });
  }
  function revealRest() {                          // loss/give-up: show one valid answer per empty cell
    for (var i = 0; i < 9; i++) {
      if (cells[i]) continue;
      var c = critAt(i);
      var opts = answers(c.row, c.col).filter(function (n) { return !used[n]; });
      cells[i] = { name: opts[0] || "—", revealed: true };
      if (opts[0]) used[opts[0]] = 1;
    }
  }
  function finish() {
    over = true; selected = -1;
    if (!won) revealRest();
    els.input.disabled = true; closeDropdown();
    if (mode === "daily") { recordDaily(won); saveDaily(); } else record(won);
    paintAll(); renderStats(); updateCounter(); showBanner();
    if (els.sr) els.sr.textContent = won ? "Grid complete!" : "Out of guesses. " + filledCount() + " of 9 filled.";
  }
  function submitGuess(name) {
    if (over || selected < 0 || !name) return;
    if (used[name]) { flash("↺ " + name + " is already on the board"); return; }   // free — no guess burned
    els.input.value = ""; closeDropdown();
    var c = critAt(selected);
    left--;
    if (fits(name, c.row) && fits(name, c.col)) {
      cells[selected] = { name: name }; used[name] = 1;
      flash("");
      if (els.sr) els.sr.textContent = name + " fits " + critLabel(c.row) + " + " + critLabel(c.col) + ".";
      if (filledCount() === 9) { won = true; finish(); return; }
      autoSelect();
    } else {
      wrong++;
      if (misses[selected].indexOf(name) < 0) misses[selected].push(name);   // remember it for this cell
      flash("✗ " + name + " doesn't fit " + critLabel(c.row) + " + " + critLabel(c.col));
      if (els.sr) els.sr.textContent = name + " doesn't fit. " + left + " guesses left.";
    }
    if (left <= 0 && !won) { won = false; finish(); return; }
    if (mode === "daily") saveDaily();
    paintAll(); updateCounter();
    if (!over) els.input.focus();
  }
  function giveUp() {
    if (over || mode === "daily") return;
    won = false; finish();
  }

  function resetState() {
    cells = [null, null, null, null, null, null, null, null, null];
    misses = [[], [], [], [], [], [], [], [], []];
    left = MAX; wrong = 0; over = false; won = false; used = {}; selected = -1;
    els.input.value = ""; els.input.disabled = false; els.banner.hidden = true; flash("");
  }
  function dealDaily() {
    pIdx = dailyIdx();
    if (pIdx < 0) { els.counter.textContent = "No grids available."; return; }
    puzzle = GRIDS[pIdx]; dealt = true;
    resetState();
    var saved = lsGet(K.daily(todayStr()), null);
    if (saved && saved.puzzle === pIdx) {
      (saved.cells || []).forEach(function (n, i) { if (n) { cells[i] = { name: n }; used[n] = 1; } });
      if (saved.misses && saved.misses.length === 9) misses = saved.misses;
      left = typeof saved.left === "number" ? saved.left : left;
      wrong = saved.wrong || 0;
      over = !!saved.done; won = !!saved.won;
    }
    renderBoard(); closeDropdown(); updateNextBtn();
    if (over) { won ? paintAll() : revealRest(); els.input.disabled = true; paintAll(); showBanner(); updateCounter(); }
    else { autoSelect(); updateCounter(); }
  }
  function deal() {
    if (mode === "daily") { dealDaily(); return; }
    if (!GRIDS.length) { els.counter.textContent = "No grids available."; return; }
    var i = Math.floor(Math.random() * GRIDS.length);
    if (GRIDS.length > 1 && i === pIdx) i = (i + 1) % GRIDS.length;
    pIdx = i; puzzle = GRIDS[pIdx]; dealt = true;
    resetState();
    renderBoard(); updateCounter(); updateNextBtn(); closeDropdown(); autoSelect();
  }

  function setMode(m) {
    mode = (m === "practice") ? "practice" : "daily";
    lsSet(K.mode, mode);
    [["daily", els.tabDaily], ["practice", els.tabPractice]].forEach(function (pr) {
      if (!pr[1]) return;
      var sel = pr[0] === mode;
      pr[1].classList.toggle("active", sel);
      pr[1].setAttribute("aria-selected", sel ? "true" : "false");
      pr[1].tabIndex = sel ? 0 : -1;
    });
    renderStats(); deal();
  }

  // --- How-to modal ----------------------------------------------------------
  var lastFocus = null;
  function openInfo() {
    if (!els.infoModal) return;
    lsSet(K.seen, true);
    lastFocus = document.activeElement;
    els.infoModal.hidden = false;
    var d = els.infoModal.firstElementChild; if (d && d.focus) d.focus();
  }
  function closeInfo() {
    if (!els.infoModal) return;
    els.infoModal.hidden = true;
    if (lastFocus && lastFocus.focus) lastFocus.focus();
    lastFocus = null;
  }
  function maybeFirstHelp() {
    if (lsGet(K.seen, false)) return false;
    openInfo();
    return true;
  }
  function onModalKey(e) {
    if (!els.infoModal || els.infoModal.hidden) return;
    if (e.key === "Escape") { if (e.preventDefault) e.preventDefault(); closeInfo(); return; }
    if (e.key !== "Tab") return;
    var dlg = els.infoModal.firstElementChild; if (!dlg) return;
    var f = dlg.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');
    if (!f.length) return;
    var first = f[0], last = f[f.length - 1];
    if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
    else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
  }

  // --- Events / init ---------------------------------------------------------
  function onKeyDown(e) {
    if (els.dropdown.hidden) return;
    if (!matches.length) { if (e.key === "Escape") closeDropdown(); return; }
    if (e.key === "ArrowDown") { e.preventDefault(); activeIndex = (activeIndex + 1) % matches.length; renderDropdown(); }
    else if (e.key === "ArrowUp") { e.preventDefault(); activeIndex = (activeIndex - 1 + matches.length) % matches.length; renderDropdown(); }
    else if (e.key === "Enter") { e.preventDefault(); if (activeIndex >= 0 && matches[activeIndex]) submitGuess(matches[activeIndex].name); }
    else if (e.key === "Escape") closeDropdown();
  }
  function onModeKey(e) {
    var order = ["daily", "practice"], i = order.indexOf(mode), n = order.length, next = null;
    if (e.key === "ArrowRight" || e.key === "ArrowDown") next = order[(i + 1) % n];
    else if (e.key === "ArrowLeft" || e.key === "ArrowUp") next = order[(i + n - 1) % n];
    else if (e.key === "Home") next = order[0];
    else if (e.key === "End") next = order[n - 1];
    if (!next) return;
    e.preventDefault(); setMode(next);
    ({ daily: els.tabDaily, practice: els.tabPractice })[next].focus();
  }
  function onGlobalKey(e) {
    if (els.infoModal && !els.infoModal.hidden) return;
    if (!over || mode === "daily") return;
    if (e.key !== " " && e.code !== "Space" && e.keyCode !== 32) return;
    if (els.view && els.view.hidden) return;
    var t = e.target;
    if (t && t.tagName && t.tagName.toUpperCase() === "BUTTON") return;
    if (e.preventDefault) e.preventDefault();
    deal();
  }

  function init() {
    els.input = $("gr-input"); els.dropdown = $("gr-dropdown"); els.board = $("gr-board");
    els.counter = $("gr-counter"); els.banner = $("gr-banner"); els.flash = $("gr-flash");
    els.next = $("gr-next"); els.giveup = $("gr-giveup"); els.stats = $("gr-stats"); els.sr = $("gr-sr");
    els.modeRow = $("gr-modes"); els.tabDaily = $("gr-daily"); els.tabPractice = $("gr-practice");
    els.view = $("thegrid-view");
    els.infoBtn = $("gr-info-btn"); els.infoModal = $("gr-info-modal"); els.infoClose = $("gr-info-close");
    if (!els.input || !GRIDS.length) return;

    els.input.addEventListener("input", refreshMatches);
    els.input.addEventListener("keydown", onKeyDown);
    els.input.addEventListener("focus", refreshMatches);
    document.addEventListener("click", function (e) { if (e.target !== els.input && els.dropdown && !els.dropdown.contains(e.target)) closeDropdown(); });
    els.next.addEventListener("click", deal);
    if (els.giveup) els.giveup.addEventListener("click", giveUp);
    els.tabDaily.addEventListener("click", function () { if (mode !== "daily") setMode("daily"); });
    els.tabPractice.addEventListener("click", function () { if (mode !== "practice") setMode("practice"); });
    if (els.modeRow) els.modeRow.addEventListener("keydown", onModeKey);
    if (els.infoBtn) els.infoBtn.addEventListener("click", openInfo);
    if (els.infoClose) els.infoClose.addEventListener("click", closeInfo);
    if (els.infoModal) els.infoModal.addEventListener("click", function (e) { if (e.target === els.infoModal) closeInfo(); });
    document.addEventListener("keydown", onModalKey);
    document.addEventListener("keydown", onGlobalKey);

    setMode(lsGet(K.mode, "daily"));
  }

  window.TheGrid = {
    onShow: function () { if (!dealt) deal(); if (maybeFirstHelp()) return; if (els.input && !over) els.input.focus(); },
    goDaily: function () { setMode("daily"); },
    goPractice: function () { setMode("practice"); },
    // internal hooks used by test.js AND build_grids.js (shared predicates)
    _peek: function () { return { mode: mode, pIdx: pIdx, puzzle: puzzle, cells: cells, misses: misses, left: left, wrong: wrong, over: over, won: won, selected: selected }; },
    _deal: deal,
    _setMode: setMode,
    _select: select,
    _submit: submitGuess,
    _shareText: shareText,
    _fits: fits,
    _answers: answers,
    _universe: universe
  };

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init);
  else init();
})();
